import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { detect, parse, stringify } from '../../main/ts/api/format-api.ts'

const corpusRoot = resolve('tmp/yarn-corpus/raw')
const corpusAvailable = existsSync(corpusRoot)
const suite = corpusAvailable ? describe : describe.skip

function isKnownInvalidArtifact(file: string, input: string): boolean {
  if (file.endsWith('.rej')) return input.startsWith('diff ') && input.includes('(rejected hunks)')
  if (input === '\n') return true
  if (!/(?:\.orig|\.save|\.backup|yarn\.lock-|yarn\.lock2)$/.test(file)) return false
  return input.includes('<<<<<<<')
    || input.startsWith(' THIS IS AN AUTOGENERATED FILE')
    || input.includes('  "integrity" "sha512-')
}

suite(
  corpusAvailable
    ? 'Yarn Classic external corpus audit'
    : 'Yarn Classic external corpus audit [skipped: gitignored tmp/yarn-corpus/raw is absent]',
  () => {
    it('strictly replays every supported classic lock and rejects only source artifacts', () => {
      const unexpected: string[] = []
      let replayed = 0
      let byteIdentical = 0
      let invalid = 0

      for (const file of readdirSync(corpusRoot).sort()) {
        if (!file.startsWith('classic')) continue
        const input = readFileSync(resolve(corpusRoot, file), 'utf8')
        const candidate = detect(input)
        if (candidate !== 'yarn-classic') {
          if (isKnownInvalidArtifact(file, input)) invalid += 1
          else unexpected.push(`${file}: detected as ${candidate ?? 'unknown'}`)
          continue
        }

        try {
          const graph = parse(input, candidate)
          const output = stringify(graph, candidate, { strict: true })
          replayed += 1
          if (output === input) byteIdentical += 1
        } catch (error) {
          if (isKnownInvalidArtifact(file, input)) invalid += 1
          else unexpected.push(`${file}: ${String((error as Error).message).slice(0, 180)}`)
        }
      }

      console.log(`classic corpus: replayed ${replayed} | byte-identical ${byteIdentical} | invalid ${invalid}`)
      expect(unexpected, 'refusals outside the exact invalid-artifact set').toEqual([])
      expect(invalid, 'conflict/backup artifacts remain outside the accepted grammar').toBe(14)
      expect(replayed).toBeGreaterThan(0)
    }, 60_000)
  },
)
