import { describe, expect, it } from 'vitest'
import { createHash } from 'node:crypto'
import { newBuilder, serializeNodeId, type Graph, type Node, type TarballPayload } from '../../main/ts/graph.ts'
import {
  parse as parseV9,
  stringify as stringifyV9,
  enrich as enrichV9,
  optimize as optimizeV9,
} from '../../main/ts/formats/yarn-berry-v9.ts'
import { parse as parseV4 } from '../../main/ts/formats/yarn-berry-v4.ts'
import {
  baseSpecOfPatchLocator,
  patchLocatorOfResolution,
  patchSourceOfLocator,
  isDegeneratePatchSource,
  irreducibleCollisionMessage,
  sortPeerContext,
  conditionToken,
  composeConditionsFromPayload,
  linkTypeOfResolution,
  nodeNameVersion,
  strippedPatchDescriptor,
  locatorQualifierOfPatchSpec,
  hasExplicitProtocol,
  isRegistryRange,
  splitOptionalDeps,
  binBlockOfNode,
  workspaceSpecOfEntry,
  nameFromResolutionLocator,
} from '../../main/ts/formats/_yarn-berry-core.ts'

const BERRY_V9_HEAD =
  '# This file is generated by running "yarn install" inside your project.\n' +
  '# Manual changes might be lost - proceed with caution!\n\n' +
  '__metadata:\n  version: 9\n  cacheKey: 10c0\n\n'

const PATCH_RES = 'lodash@patch:lodash@npm%3A4.17.21#./.yarn/patches/lodash-npm-4.17.21-6382451519.patch::version=4.17.21&hash=858da5&locator=case-patch-yarn%40workspace%3A.'
const PATCH_SOURCE = './.yarn/patches/lodash-npm-4.17.21-6382451519.patch'

describe('patchLocatorOfResolution', () => {
  it('peels the `<name>@patch:` prefix, keeps a bare `patch:` verbatim', () => {
    expect(patchLocatorOfResolution(PATCH_RES)).toBe(PATCH_RES.slice('lodash@'.length))
    expect(patchLocatorOfResolution('patch:foo#p')).toBe('patch:foo#p')
    expect(patchLocatorOfResolution('lodash@npm:4.17.21')).toBeUndefined()
  })
})

describe('baseSpecOfPatchLocator', () => {
  it('decodes the patched base descriptor', () => {
    const locator = patchLocatorOfResolution(PATCH_RES)!
    expect(baseSpecOfPatchLocator(locator)).toBe('lodash@npm:4.17.21')
    expect(baseSpecOfPatchLocator('not-a-patch')).toBeUndefined()
  })

  it('returns undefined on an undecodable percent-escape', () => {
    expect(baseSpecOfPatchLocator('patch:%zz#p')).toBeUndefined()
  })
})

describe('patchSourceOfLocator', () => {
  it('extracts the fragment between `#` and the `::` param block', () => {
    const locator = patchLocatorOfResolution(PATCH_RES)!
    expect(patchSourceOfLocator(locator)).toBe(PATCH_SOURCE)
    expect(patchSourceOfLocator('patch:foo')).toBeUndefined()
  })
})

describe('isDegeneratePatchSource', () => {
  it('empty/dot-only path is degenerate; a real relative path is not', () => {
    expect(isDegeneratePatchSource('')).toBe(true)
    expect(isDegeneratePatchSource('.')).toBe(true)
    expect(isDegeneratePatchSource('%2E')).toBe(true) // decodes to '.'
    expect(isDegeneratePatchSource('./patches/x.patch')).toBe(false)
    expect(isDegeneratePatchSource('/abs/path')).toBe(false)
    expect(isDegeneratePatchSource('%zz')).toBe(false)
  })
})

describe('strippedPatchDescriptor', () => {
  it('collapses an entry locator and a bare descriptor to one key', () => {
    const entry = 'lodash@patch:lodash@npm%3A4.17.21#./p.patch::version=4.17.21&hash=858da5'
    const descriptor = 'lodash@patch:lodash@npm%3A4.17.21#./p.patch'
    expect(strippedPatchDescriptor(entry)).toBe(descriptor)
    expect(strippedPatchDescriptor(descriptor)).toBe(descriptor)
    expect(strippedPatchDescriptor('lodash@npm:4.17.21')).toBeUndefined()
  })
})

describe('locatorQualifierOfPatchSpec', () => {
  it('extracts the `locator=` consumer qualifier', () => {
    const spec = 'lodash@npm%3A4.17.21#./p.patch::version=4.17.21&hash=858da5&locator=root%40workspace%3A.'
    expect(locatorQualifierOfPatchSpec(spec)).toBe('root%40workspace%3A.')
    expect(locatorQualifierOfPatchSpec('lodash@npm%3A4#./p.patch')).toBeUndefined()
  })
})

describe('hasExplicitProtocol', () => {
  it('recognises a lowercase protocol prefix, rejects bare/URL-authority ranges', () => {
    expect(hasExplicitProtocol('npm:^1')).toBe(true)
    expect(hasExplicitProtocol('patch:foo#p')).toBe(true)
    expect(hasExplicitProtocol('^1.2.3')).toBe(false)
    expect(hasExplicitProtocol('workspace:*')).toBe(true)
  })
})

describe('isRegistryRange', () => {
  it('npm: and bare are registry; explicit non-npm protocols are not', () => {
    expect(isRegistryRange('npm:^1')).toBe(true)
    expect(isRegistryRange('^1.2.3')).toBe(true)
    expect(isRegistryRange('workspace:*')).toBe(false)
    expect(isRegistryRange('patch:foo#p')).toBe(false)
  })
})

describe('nodeNameVersion', () => {
  it('strips a peerContext tail and a +slot suffix down to name@version', () => {
    expect(nodeNameVersion('lodash@4.17.21')).toBe('lodash@4.17.21')
    expect(nodeNameVersion('react@18.2.0(react-dom@18.2.0)')).toBe('react@18.2.0')
    expect(nodeNameVersion('@scope/pkg@1.0.0+patch=abcd')).toBe('@scope/pkg@1.0.0')
    expect(nodeNameVersion('lodash')).toBeUndefined()
  })
})

describe('linkTypeOfResolution', () => {
  it('reports soft for link:/portal: and a file: DIRECTORY, hard for a file: ARCHIVE and everything else', () => {
    expect(linkTypeOfResolution('pkg@link:../x')).toBe('soft')
    expect(linkTypeOfResolution('pkg@portal:packages/y')).toBe('soft')
    expect(linkTypeOfResolution('pkg@file:../dir')).toBe('soft')
    expect(linkTypeOfResolution('pkg@file:./vendor/x.tgz')).toBe('hard')
    expect(linkTypeOfResolution('pkg@file:./vendor/x.tgz::locator=root%40workspace%3A.')).toBe('hard')
    expect(linkTypeOfResolution('pkg@npm:4.17.21')).toBe('hard')
    // An unparseable locator falls back to hard, the safe default.
    expect(linkTypeOfResolution('not-a-locator')).toBe('hard')
    expect(linkTypeOfResolution(undefined)).toBe('hard')
  })
})

describe('conditionToken', () => {
  it('migrates a leading `!` run to a prefix before the axis name, cancelling even runs', () => {
    expect(conditionToken('os', 'darwin')).toBe('os=darwin')
    expect(conditionToken('os', '!win32')).toBe('!os=win32')
    expect(conditionToken('os', '!!win32')).toBe('os=win32')
  })
})

describe('composeConditionsFromPayload', () => {
  it('joins os/cpu/libc, OR-grouping multi-value axes', () => {
    expect(composeConditionsFromPayload({ os: ['darwin'], cpu: ['arm64'] })).toBe('os=darwin & cpu=arm64')
    expect(composeConditionsFromPayload({ os: ['linux'], cpu: ['x64'], libc: ['musl'] }))
      .toBe('os=linux & cpu=x64 & libc=musl')
    expect(composeConditionsFromPayload({ os: ['linux', 'android'] })).toBe('(os=linux | os=android)')
    expect(composeConditionsFromPayload({})).toBeUndefined()
    expect(composeConditionsFromPayload(undefined)).toBeUndefined()
  })
})

describe('sortPeerContext', () => {
  it('orders by package name then full id', () => {
    expect(sortPeerContext(['b@1.0.0', 'a@2.0.0', 'a@1.0.0'])).toEqual(['a@1.0.0', 'a@2.0.0', 'b@1.0.0'])
  })
})

describe('nameFromResolutionLocator', () => {
  it('returns the name only for an `<name>@npm:<rest>` locator', () => {
    expect(nameFromResolutionLocator('lodash@npm:4.17.21')).toBe('lodash')
    expect(nameFromResolutionLocator('@scope/pkg@npm:1.0.0')).toBe('@scope/pkg')
    // Non-npm protocols / URL-shaped strings return undefined.
    expect(nameFromResolutionLocator('pkg@workspace:.')).toBeUndefined()
    expect(nameFromResolutionLocator('https://registry.npmjs.org/ms/-/ms-2.1.3.tgz')).toBeUndefined()
  })
})

describe('workspaceSpecOfEntry', () => {
  it('prefers the resolution workspace path, else a concrete-path spec', () => {
    const mkSpec = (name: string, protocol: string, spec: string) => ({ name, protocol, spec, raw: `${protocol}:${spec}` })
    // resolution wins.
    expect(workspaceSpecOfEntry('pkg@workspace:packages/x', [mkSpec('pkg', 'npm', '1.0.0')], mkSpec('pkg', 'npm', '1.0.0')))
      .toBe('packages/x')
    // concrete-path workspace spec preferred over a range marker.
    const specs = [mkSpec('pkg', 'workspace', '^'), mkSpec('pkg', 'workspace', 'packages/y')]
    expect(workspaceSpecOfEntry(undefined, specs, specs[0]!)).toBe('packages/y')
    // fall back to first.spec when first is a workspace protocol.
    const wsFirst = mkSpec('pkg', 'workspace', '.')
    expect(workspaceSpecOfEntry(undefined, [wsFirst], wsFirst)).toBe('.')
    const npmFirst = mkSpec('pkg', 'npm', '1.0.0')
    expect(workspaceSpecOfEntry(undefined, [npmFirst], npmFirst)).toBeUndefined()
  })
})

describe('binBlockOfNode', () => {
  it('maps a STRING bin to the unscoped command name', () => {
    const node: Node = { id: '@babel/parser@7.0.0', name: '@babel/parser', version: '7.0.0', peerContext: [] }
    expect(binBlockOfNode(node, { bin: 'bin/parser.js' } as TarballPayload)).toEqual({ parser: 'bin/parser.js' })
    // A record bin is sorted by key.
    const node2: Node = { id: 'tool@1.0.0', name: 'tool', version: '1.0.0', peerContext: [] }
    expect(binBlockOfNode(node2, { bin: { z: 'z.js', a: 'a.js' } } as TarballPayload)).toEqual({ a: 'a.js', z: 'z.js' })
    expect(binBlockOfNode(node2, {} as TarballPayload)).toBeUndefined()
  })
})

describe('splitOptionalDeps', () => {
  it('partitions a dependencies block by the dependenciesMeta.optional flag', () => {
    const deps = { a: 'npm:^1', b: 'npm:^2', c: 'npm:^3' }
    const meta = { b: { optional: 'true' }, c: { built: 'true' } }
    expect(splitOptionalDeps(deps, meta)).toEqual({
      regular: { a: 'npm:^1', c: 'npm:^3' }, // c is `built`, not `optional`
      optional: { b: 'npm:^2' },
    })
    expect(splitOptionalDeps(deps, undefined)).toEqual({ regular: deps, optional: undefined })
    expect(splitOptionalDeps(undefined, meta)).toEqual({ regular: undefined, optional: undefined })
  })
})

describe('irreducibleCollisionMessage', () => {
  it('selects the link/portal hint when a colliding resolution carries @link:/@portal:', () => {
    const prior = { key: 'pkg@link:a', value: { version: '1.0.0', resolution: 'pkg@link:packages/a' }, specs: [{ name: 'pkg', protocol: 'link', spec: 'packages/a', raw: 'link:packages/a' }] }
    const current = { key: 'pkg@link:b', value: { version: '1.0.0', resolution: 'pkg@link:packages/b' }, specs: [{ name: 'pkg', protocol: 'link', spec: 'packages/b', raw: 'link:packages/b' }] }
    const msg = irreducibleCollisionMessage('pkg@1.0.0', 'pkg@link:b', [prior, current])
    expect(msg).toContain('workspace link:')
    expect(msg).toContain('resolutions:')
  })

  it('selects the patch hint when a colliding resolution carries @patch:', () => {
    const prior = { key: 'pkg@patch:a', value: { version: '1.0.0', resolution: 'pkg@patch:pkg@npm%3A1.0.0#a' }, specs: [{ name: 'pkg', protocol: 'patch', spec: '', raw: '' }] }
    const current = { key: 'pkg@patch:b', value: { version: '1.0.0', resolution: 'pkg@patch:pkg@npm%3A1.0.0#b' }, specs: [{ name: 'pkg', protocol: 'patch', spec: '', raw: '' }] }
    const msg = irreducibleCollisionMessage('pkg@1.0.0', 'pkg@patch:b', [prior, current])
    expect(msg).toContain('patch: collision')
  })

  it('selects the bind hint when a colliding resolution carries a `::` modifier', () => {
    const prior = { key: 'pkg@npm:1.0.0::a', value: { version: '1.0.0', resolution: 'pkg@npm:1.0.0::__archiveUrl=x' }, specs: [{ name: 'pkg', protocol: 'npm', spec: '', raw: '' }] }
    const current = { key: 'pkg@npm:1.0.0::b', value: { version: '1.0.0', resolution: 'pkg@npm:1.0.0::__archiveUrl=y' }, specs: [{ name: 'pkg', protocol: 'npm', spec: '', raw: '' }] }
    const msg = irreducibleCollisionMessage('pkg@1.0.0', 'pkg@npm:1.0.0::b', [prior, current])
    expect(msg).toContain('bind modifier')
  })
})

describe('parse', () => {
  it('warns YARN_BERRY_BAD_ENTRY and skips a non-block entry value', () => {
    const graph = parseV9(BERRY_V9_HEAD + '"junk@npm:1.0.0": not-a-block\n')
    expect(graph.diagnostics().some(d => d.code === 'YARN_BERRY_BAD_ENTRY')).toBe(true)
  })

  it('throws PARSE_FAILED on an entry missing `version`', () => {
    expect(() => parseV9(
      BERRY_V9_HEAD +
      '"lodash@npm:4.17.21":\n' +
      '  resolution: "lodash@npm:4.17.21"\n',
    )).toThrow(/missing 'version'/)
  })

  it('throws IRREDUCIBLE_LOSS when two separate entry blocks collapse onto one NodeId', () => {
    // Berry has no merge path, unlike classic: two distinct entry blocks that
    // serialize to the same NodeId (same name@version, both plain npm registry,
    // no discriminator) are an irreducible collision and throw with the hint.
    expect(() => parseV9(
      BERRY_V9_HEAD +
      '"lodash@npm:4.17.21":\n' +
      '  version: 4.17.21\n' +
      '  resolution: "lodash@npm:4.17.21"\n\n' +
      '"lodash@npm:^4.0.0":\n' +
      '  version: 4.17.21\n' +
      '  resolution: "lodash@npm:4.17.21"\n',
    )).toThrow(/two entries collapse onto NodeId lodash@4\.17\.21/)
  })

  it('parses a patch entry and derives a canonical patch fingerprint node', () => {
    const graph = parseV9(
      BERRY_V9_HEAD +
      '"case-patch@workspace:.":\n' +
      '  version: 0.0.0-use.local\n' +
      '  resolution: "case-patch@workspace:."\n' +
      '  dependencies:\n' +
      '    lodash: "npm:4.17.21"\n' +
      '  languageName: unknown\n' +
      '  linkType: soft\n\n' +
      '"lodash@npm:4.17.21":\n' +
      '  version: 4.17.21\n' +
      '  resolution: "lodash@patch:lodash@npm%3A4.17.21#./.yarn/patches/lodash.patch::version=4.17.21&hash=858da5&locator=case-patch%40workspace%3A."\n' +
      '  checksum: 10c0/' + createHash('sha512').update('z').digest('hex') + '\n' +
      '  languageName: node\n' +
      '  linkType: hard\n',
    )
    const lodash = Array.from(graph.nodes()).find(n => n.name === 'lodash')
    expect(lodash).toBeDefined()
    expect(lodash!.patch).toBeDefined()
  })

  it('parses a patch entry and re-emits its `@patch:` resolution + patched base descriptor', () => {
    const checksum = createHash('sha512').update('lodash-zip').digest('hex')
    const input =
      BERRY_V9_HEAD +
      '"root@workspace:.":\n' +
      '  version: 0.0.0-use.local\n' +
      '  resolution: "root@workspace:."\n' +
      '  dependencies:\n' +
      '    lodash: "npm:4.17.21"\n' +
      '  languageName: unknown\n' +
      '  linkType: soft\n\n' +
      '"lodash@npm:4.17.21":\n' +
      '  version: 4.17.21\n' +
      '  resolution: "lodash@patch:lodash@npm%3A4.17.21#./.yarn/patches/lodash.patch::version=4.17.21&hash=858da5&locator=root%40workspace%3A."\n' +
      `  checksum: 10c0/${checksum}\n` +
      '  languageName: node\n' +
      '  linkType: hard\n'
    const graph = parseV9(input)
    const out = stringifyV9(graph)
    // The verbatim `@patch:` locator round-trips as the resolution.
    expect(out).toContain('resolution: "lodash@patch:lodash@npm%3A4.17.21#./.yarn/patches/lodash.patch::version=4.17.21&hash=858da5&locator=root%40workspace%3A."')
    // The entry key carries both the patched-base descriptor and the patch locator.
    expect(out).toContain('lodash@npm:4.17.21')
    expect(out).toContain('lodash@patch:')
  })

  it.each([
    ['builtin', 'npm%3A5.0.0'],
    ['builtin', '5.0.0'],
    ['~builtin', 'npm%3A5.0.0'],
    ['~builtin', '5.0.0'],
    ['optional!builtin', 'npm%3A5.0.0'],
    ['optional!builtin', '5.0.0'],
  ])(
    'recognises %s syntax with %s inner locator as an intrinsic builtin patch',
    (syntax, inner) => {
      const source = `${syntax}<compat/typescript>`
      const locator =
        `typescript@patch:typescript@${inner}#${source}::version=5.0.0&hash=abc123`
      const input =
        BERRY_V9_HEAD +
        '"root@workspace:.":\n' +
        '  version: 0.0.0-use.local\n' +
        '  resolution: "root@workspace:."\n' +
        '  dependencies:\n' +
        `    typescript: "patch:typescript@${inner}#${source}"\n` +
        '  languageName: unknown\n' +
        '  linkType: soft\n\n' +
        `"${locator}":\n` +
        '  version: 5.0.0\n' +
        `  resolution: "${locator}"\n` +
        '  languageName: node\n' +
        '  linkType: hard\n'
      const graph = parseV9(input, { workspaceRoot: '/definitely/not/a/repository' })
      const diagnostics = graph.diagnostics()
        .filter(diagnostic => diagnostic.code === 'YARN_BERRY_PATCH_UNRESOLVED')
      expect(diagnostics).toHaveLength(1)
      expect(diagnostics[0]?.message).toContain(
        'builtin compatibility patch has no on-disk source',
      )
      expect(diagnostics[0]?.message).not.toContain('patch file is unavailable')
      expect(diagnostics[0]?.message).not.toContain('workspaceRoot is unavailable')
      const ts = Array.from(graph.nodes()).find(n => n.name === 'typescript')
      expect(ts!.patch).toBeDefined()
    },
  )

  it('diagnoses UNRESOLVED_DEP for a bare `patch:` descriptor ambiguous across >=2 patch entries', () => {
    const input =
      BERRY_V9_HEAD +
      '"a@workspace:packages/a":\n' +
      '  version: 0.0.0-use.local\n' +
      '  resolution: "a@workspace:packages/a"\n' +
      '  dependencies:\n' +
      '    lodash: "patch:lodash@npm%3A4.17.21#./p.patch"\n' +
      '  languageName: unknown\n' +
      '  linkType: soft\n\n' +
      '"lodash@patch:lodash@npm%3A4.17.21#./p.patch::version=4.17.21&hash=111&locator=x%40workspace%3A.":\n' +
      '  version: 4.17.21\n' +
      '  resolution: "lodash@patch:lodash@npm%3A4.17.21#./p.patch::version=4.17.21&hash=111&locator=x%40workspace%3A."\n' +
      '  languageName: node\n' +
      '  linkType: hard\n\n' +
      '"lodash@patch:lodash@npm%3A4.17.21#./p.patch::version=4.17.21&hash=222&locator=y%40workspace%3A.":\n' +
      '  version: 4.17.21\n' +
      '  resolution: "lodash@patch:lodash@npm%3A4.17.21#./p.patch::version=4.17.21&hash=222&locator=y%40workspace%3A."\n' +
      '  languageName: node\n' +
      '  linkType: hard\n'
    const graph = parseV9(input)
    // The bare consumer descriptor cannot pick between the two `::locator=`-qualified
    // patch entries (its own locator matches neither) → ambiguous UNRESOLVED_DEP.
    expect(graph.diagnostics().some(d =>
      d.code === 'YARN_BERRY_UNRESOLVED_DEP' && /ambiguous across 2 patch entries/.test(d.message),
    )).toBe(true)
  })

  it('diagnoses an ambiguous dist-tag (`npm:latest`) against >=2 siblings and drops the edge', () => {
    const graph = parseV9(
      BERRY_V9_HEAD +
      '"root@workspace:.":\n' +
      '  version: 0.0.0-use.local\n' +
      '  resolution: "root@workspace:."\n' +
      '  dependencies:\n' +
      '    lodash: "npm:latest"\n' +
      '  languageName: unknown\n' +
      '  linkType: soft\n\n' +
      '"lodash@npm:4.17.20":\n' +
      '  version: 4.17.20\n' +
      '  resolution: "lodash@npm:4.17.20"\n' +
      '  languageName: node\n' +
      '  linkType: hard\n\n' +
      '"lodash@npm:4.17.21":\n' +
      '  version: 4.17.21\n' +
      '  resolution: "lodash@npm:4.17.21"\n' +
      '  languageName: node\n' +
      '  linkType: hard\n',
    )
    const codes = graph.diagnostics().map(d => d.code)
    expect(codes).toContain('YARN_BERRY_V9_AMBIGUOUS_RESOLUTION')
    expect(codes).toContain('YARN_BERRY_V9_RESOLUTION_PIN_UNRESOLVED')
  })

  it('preserves an absent-target dep and round-trips it through optimize()', () => {
    const graph = parseV9(
      BERRY_V9_HEAD +
      '"root@workspace:.":\n' +
      '  version: 0.0.0-use.local\n' +
      '  resolution: "root@workspace:."\n' +
      '  dependencies:\n' +
      '    ghost: "npm:^1.0.0"\n' +
      '  languageName: unknown\n' +
      '  linkType: soft\n',
    )
    expect(graph.diagnostics().map(d => d.code)).toContain('YARN_BERRY_UNRESOLVED_DEP')
    // optimize keeps the workspace root + its unresolved-dep sidecar; the re-emit
    // still carries the ghost line.
    const { graph: opt } = optimizeV9(graph)
    expect(stringifyV9(opt)).toContain('ghost: "npm:^1.0.0"')
  })
})

describe('enrich', () => {
  it('on a graph carrying an unresolved-dep sidecar runs clean and preserves the ghost line', () => {
    const graph = parseV9(
      BERRY_V9_HEAD +
      '"root@workspace:.":\n' +
      '  version: 0.0.0-use.local\n' +
      '  resolution: "root@workspace:."\n' +
      '  dependencies:\n' +
      '    ghost: "npm:^1.0.0"\n' +
      '  languageName: unknown\n' +
      '  linkType: soft\n',
    )
    const { graph: enriched } = enrichV9(graph)
    expect(stringifyV9(enriched)).toContain('ghost: "npm:^1.0.0"')
  })
})

describe('stringify', () => {
  function buildRegistryNodeGraph(): Graph {
    const b = newBuilder()
    const id = serializeNodeId('lodash', '4.17.21', [])
    b.addNode({ id, name: 'lodash', version: '4.17.21', peerContext: [] })
    b.setTarball({ name: 'lodash', version: '4.17.21' }, {
      resolution: { type: 'tarball', url: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz' },
    })
    return b.seal()
  }

  it('emits a canonical npm registry node as `<name>@npm:<version>` with node linkType/languageName', () => {
    const out = stringifyV9(buildRegistryNodeGraph())
    expect(out).toContain('"lodash@npm:4.17.21":')
    expect(out).toContain('  resolution: "lodash@npm:4.17.21"')
    expect(out).toContain('  languageName: node')
    expect(out).toContain('  linkType: hard')
  })

  it('composes a `conditions:` scalar from a completion-style os/cpu payload and emits it bare', () => {
    const b = newBuilder()
    const id = serializeNodeId('@esbuild/darwin-arm64', '0.19.0', [])
    b.addNode({ id, name: '@esbuild/darwin-arm64', version: '0.19.0', peerContext: [] })
    b.setTarball({ name: '@esbuild/darwin-arm64', version: '0.19.0' }, {
      resolution: { type: 'tarball', url: 'https://registry.npmjs.org/@esbuild/darwin-arm64/-/darwin-arm64-0.19.0.tgz' },
      os: ['darwin'],
      cpu: ['arm64'],
    } as TarballPayload)
    const out = stringifyV9(b.seal())
    // Emitted bare (no surrounding quotes) even though the value has spaces + `&`.
    expect(out).toContain('  conditions: os=darwin & cpu=arm64\n')
  })

  it('v4 (conditionsAllowed) still emits conditions; a config with conditions disabled would diagnose', () => {
    const input =
      '# This file is generated by running "yarn install" inside your project.\n' +
      '# Manual changes might be lost - proceed with caution!\n\n' +
      '__metadata:\n  version: 4\n  cacheKey: 8\n\n' +
      '"@esbuild/darwin-arm64@npm:0.19.0":\n' +
      '  version: 0.19.0\n' +
      '  resolution: "@esbuild/darwin-arm64@npm:0.19.0"\n' +
      '  conditions: os=darwin & cpu=arm64\n' +
      '  languageName: node\n' +
      '  linkType: hard\n'
    const graph = parseV4(input)
    const node = Array.from(graph.nodes())[0]!
    expect(node.name).toBe('@esbuild/darwin-arm64')
  })

  it('throws MISSING_REQUIRED_FIELD when a dep edge lacks a range on emit', () => {
    const b = newBuilder()
    const root = serializeNodeId('root', '0.0.0-use.local', [])
    const dep = serializeNodeId('dep', '1.0.0', [])
    b.addNode({ id: root, name: 'root', version: '0.0.0-use.local', peerContext: [], workspacePath: '' })
    b.addNode({ id: dep, name: 'dep', version: '1.0.0', peerContext: [] })
    b.setTarball({ name: 'dep', version: '1.0.0' }, { resolution: { type: 'tarball', url: 'https://registry.npmjs.org/dep/-/dep-1.0.0.tgz' } })
    // A dep edge with no attrs at all → no range → emit throws.
    b.addEdge(root, dep, 'dep')
    const graph = b.seal()
    expect(() => stringifyV9(graph)).toThrow(/requires attrs\.range for emit/)
  })
})
