// #102 — ConvertOptions.manifests.
//
// `convert()` threads `manifests` into its underlying `parse()`, so a yarn-family
// source honours its `resolutions`/`overrides` pins on convert (the Bug #99
// override map bridges a pinned, possibly-NON-satisfying descriptor back to its
// node). Without manifests the non-satisfying pin's edge stays dropped, so the
// converted output omits it; with manifests the edge survives the conversion.
//
// DECISION (owner): convert stays a pure parse→stringify — the captured overrides
// are NOT auto-threaded into the stringify `overrides` slot (so the TARGET lock's
// own overrides block is unaffected; only the resolved GRAPH changes).

import { describe, expect, it } from 'vitest'
import { convert, parse, stringify } from '../../main/ts/index.ts'
import type { Manifest } from '../../main/ts/graph.ts'

// root declares csstype `npm:^3.1.3`; the pinned entry key is `csstype@npm:3.0.9`
// (a `resolutions` rewrite). Two csstype entries exist (3.0.9 + 2.6.21) and
// `^3.1.3` is satisfied by NEITHER, so Rung 3 semver has ≥2 candidates and no
// satisfier → DROP. Only the override map (from the manifest) can bridge the
// non-satisfying pin. (A single csstype entry would Rung-3-short-circuit even
// without a manifest, masking the effect — two non-satisfying siblings force the
// drop, exactly the backstage real-world shape.)
const BERRY_LOCK = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10

"csstype@npm:3.0.9":
  version: 3.0.9
  resolution: "csstype@npm:3.0.9"
  checksum: 10/aaaa
  languageName: node
  linkType: hard

"csstype@npm:^2.5.2":
  version: 2.6.21
  resolution: "csstype@npm:2.6.21"
  checksum: 10/bbbb
  languageName: node
  linkType: hard

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    csstype: "npm:^3.1.3"
  languageName: unknown
  linkType: soft
`

const MANIFESTS: Record<string, Manifest> = {
  '': { name: 'root', native: { yarnResolutions: { 'csstype@npm:^3.1.3': '3.0.9' } } },
}

// The importer block (`.:` … up to the next top-level section) is where a root
// dependency surfaces in a pnpm lock. Isolating it avoids matching the orphan
// `packages:` entries (which list every node regardless of reachability, since
// convert is parse→stringify with no optimize).
function importerBlock(out: string): string {
  const start = out.indexOf('importers:')
  const pkgs = out.indexOf('\npackages:', start)
  return out.slice(start, pkgs >= 0 ? pkgs : undefined)
}

describe('#102 — convert() honours a resolutions pin via manifests', () => {
  it('WITHOUT manifests: the non-satisfying pin is dropped → no csstype dependency under the importer', async () => {
    const out = await convert(BERRY_LOCK, { from: 'yarn-berry-v8', to: 'pnpm-v9', strict: false })
    // The root→csstype edge was dropped (no override map, no semver satisfier), so
    // the importer carries no csstype dependency.
    expect(importerBlock(out)).not.toMatch(/csstype/)
  })

  it('WITH manifests: the override map bridges the pin → csstype dependency appears under the importer', async () => {
    const out = await convert(BERRY_LOCK, { from: 'yarn-berry-v8', to: 'pnpm-v9', manifests: MANIFESTS, strict: false })
    // The restored edge re-points root onto the pinned csstype 3.0.9 node, so the
    // importer now carries the csstype dependency resolved to 3.0.9.
    const importer = importerBlock(out)
    expect(importer).toMatch(/csstype/)
    expect(importer).toMatch(/3\.0\.9/)
  })

  it('matches the equivalent parse({manifests}) → stringify pipeline', async () => {
    // convert is exactly parse(from, …, { manifests }) → stringify(to, …); no
    // override auto-threading. Prove equality against the manual pipeline.
    const viaConvert = await convert(BERRY_LOCK, { from: 'yarn-berry-v8', to: 'pnpm-v9', manifests: MANIFESTS, strict: false })
    const g = parse('yarn-berry-v8', BERRY_LOCK, { manifests: MANIFESTS })
    const viaPipeline = stringify('pnpm-v9', g, { strict: false })
    expect(viaConvert).toBe(viaPipeline)
  })
})

// A classic yarn.lock encodes NO project root (unlike npm's `""` entry, berry's
// `root@workspace:.`, pnpm importers, bun workspaces). Its root identity can come
// only from `manifests`, so the public `parse`/`convert` must run the
// manifest-driven `enrich` to synthesize the declared root. Without manifests,
// target adapters preserve ordinary packages beneath a neutral synthetic root,
// but project identity/declarations remain unknown and the output cannot be
// certified against the real project manifest. Reported externally against
// snapshot.92 (the flagship synp `yarn.lock → package-lock.json` direction).
describe('rootless yarn-classic source is re-rooted from manifests', () => {
  const YARN = `# yarn lockfile v1
chalk@^2.4.2:
  version "2.4.2"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-2.4.2.tgz#cd42541677a54333cf541a49108c1432b44c9424"
  integrity sha512-Mti+
  dependencies:
    ansi-styles "^3.2.1"
ansi-styles@^3.2.1:
  version "3.2.1"
  resolved "https://registry.yarnpkg.com/ansi-styles/-/ansi-styles-3.2.1.tgz#41fbb642"
  integrity sha512-VT0Z
`
  const MAN: Record<string, Manifest> = {
    '': { name: 'app', version: '1.0.0', dependencies: { chalk: '^2.4.2' } },
  }

  it('convert → npm-3 synthesizes the declared root, keeping the dependency as its own node', async () => {
    const npm3 = JSON.parse(await convert(YARN, { from: 'yarn-classic', to: 'npm-3', manifests: MAN, strict: false })) as {
      name: string
      packages: Record<string, { name?: string; dependencies?: Record<string, string> }>
    }
    expect(npm3.name).toBe('app')                                  // root is the declared project, not `chalk`
    expect(npm3.packages['']?.dependencies).toEqual({ chalk: '^2.4.2' })
    expect('node_modules/chalk' in npm3.packages).toBe(true)      // the promoted dep no longer vanishes
  })

  it('parse().roots() is the synthesized root', () => {
    const g = parse('yarn-classic', YARN, { manifests: MAN })
    expect(Array.from(g.roots())).toEqual(['app@1.0.0'])
  })

  it('the pnpm importer lists the real root dependency (chalk), not a transitive', async () => {
    const out = await convert(YARN, { from: 'yarn-classic', to: 'pnpm-v9', manifests: MAN, strict: false })
    const importer = out.slice(out.indexOf('importers:'), out.indexOf('\npackages:'))
    expect(importer).toMatch(/chalk:/)
    expect(importer).not.toMatch(/ansi-styles:/)
  })

  it('synthesis is manifest-gated — without manifests the rootless source is left as-is', () => {
    // No manifests ⇒ no project-identity invention. Target emitters may add
    // their native neutral root, but the source graph has no declared root.
    const g = parse('yarn-classic', YARN)
    expect(Array.from(g.roots())).not.toContain('app@1.0.0')
  })

  it('synthesizes an INDEPENDENT member declared in manifests but absent from the lock', async () => {
    // yarn 1 records a member in the lock only when something depends on it; an
    // independent member has no lock entry, so its node + declared dep edges are
    // synthesized from its manifest. Here `@s/a` requires chalk, which IS in the
    // lock, so the member converts completely (member entry + top-level symlink).
    const out = JSON.parse(await convert(YARN, {
      from: 'yarn-classic',
      to: 'npm-3',
      strict: false,
      manifests: {
        ...MAN,
        'packages/a': { name: '@s/a', version: '1.0.0', dependencies: { chalk: '^2.4.2' } },
      },
    })) as { packages: Record<string, { link?: boolean; resolved?: string; dependencies?: Record<string, string> }> }
    expect(out.packages['packages/a']?.dependencies).toEqual({ chalk: '^2.4.2' })
    expect(out.packages['node_modules/@s/a']).toEqual({ resolved: 'packages/a', link: true })
  })
})

// yarn 1 records each workspace member as a `file:` local entry, so members ARE in
// the lock (with their own `dependencies:` block). `enrich` recognises the member
// (its `resolved: file:…` surfaces as a `directory` resolution — NOT an external
// tarball) and marks its `workspacePath`; the npm emit then re-emits it as a proper
// npm workspace member: a `packages/<path>` entry carrying its deps + a top-level
// `node_modules/<name>` symlink. Verified against a real yarn 1 workspace: the
// converted lock passes `npm ci` byte-clean.
describe('yarn-classic workspace members (file: entries) re-emit as npm workspace members', () => {
  const YARN = `# yarn lockfile v1
"@ws/a@1.0.0", "@ws/a@file:packages/a":
  version "1.0.0"
  resolved "file:packages/a"
  dependencies:
    lodash "4.17.21"
"@ws/b@file:packages/b":
  version "1.0.0"
  resolved "file:packages/b"
  dependencies:
    "@ws/a" "1.0.0"
lodash@4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffaae8454cf0b3df370c3d6911c"
  integrity sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvKw==
`
  const MAN: Record<string, Manifest> = {
    '': { name: 'root', version: '1.0.0' },
    'packages/a': { name: '@ws/a', version: '1.0.0', dependencies: { lodash: '4.17.21' } },
    'packages/b': { name: '@ws/b', version: '1.0.0', dependencies: { '@ws/a': '1.0.0' } },
  }

  it('emits packages/<path> member entries + node_modules/<name> links, and does not warn', async () => {
    const codes: string[] = []
    const out = JSON.parse(await convert(YARN, {
      from: 'yarn-classic', to: 'npm-3', manifests: MAN, strict: false, onDiagnostic: d => codes.push(d.code),
    })) as { packages: Record<string, { link?: boolean; resolved?: string; dependencies?: Record<string, string> }> }

    // Member entries carry their own dependencies.
    expect(out.packages['packages/a']?.dependencies).toEqual({ lodash: '4.17.21' })
    expect(out.packages['packages/b']?.dependencies).toEqual({ '@ws/a': '1.0.0' })
    // Top-level symlinks point at the member paths (npm's workspace shape).
    expect(out.packages['node_modules/@ws/a']).toEqual({ resolved: 'packages/a', link: true })
    expect(out.packages['node_modules/@ws/b']).toEqual({ resolved: 'packages/b', link: true })
    // A member present in the lock is complete — no drop warning.
    expect(codes).not.toContain('YARN_CLASSIC_WORKSPACE_MEMBER_DEPS_UNSYNTHESISED')
  })
})

// A workspace member whose package NAME collides with an external published package
// already in the lock must still be synthesized. Real yarn 1 links the root
// `node_modules/<name>` to the LOCAL member and nests the external copy under its
// consumer. Guarding member synthesis on `graph.byName(name).length > 0` (any
// same-name node) wrongly skipped the member — it vanished and `npm ci` reported
// "Missing … from lock file". Verified against `npm ci`: byte-clean, with
// `node_modules/is-number` resolving to the local 99.0.0.
describe('yarn-classic workspace member colliding with an external package name is not dropped', () => {
  const YARN = `# yarn lockfile v1
is-number@^7.0.0:
  version "7.0.0"
  resolved "https://registry.yarnpkg.com/is-number/-/is-number-7.0.0.tgz#7535345b896734d5f80c4d06c50955527a14f12b"
  integrity sha512-41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==
`
  const MAN: Record<string, Manifest> = {
    '': { name: 'root', version: '1.0.0' },
    'packages/localnum': { name: 'is-number', version: '99.0.0' },
    'packages/consumer': { name: '@c/consumer', version: '1.0.0', dependencies: { 'is-number': '^7.0.0' } },
  }

  it('synthesizes the local member + links the root node_modules to it, nesting the external copy', async () => {
    const codes: string[] = []
    const out = JSON.parse(await convert(YARN, {
      from: 'yarn-classic', to: 'npm-3', manifests: MAN, strict: false, onDiagnostic: d => codes.push(d.code),
    })) as { packages: Record<string, { link?: boolean; resolved?: string; name?: string; version?: string }> }

    // The local member (is-number@99) appears and wins the root symlink.
    expect(out.packages['packages/localnum']).toEqual({ name: 'is-number', version: '99.0.0' })
    expect(out.packages['node_modules/is-number']).toEqual({ resolved: 'packages/localnum', link: true })
    // The external is-number@7 nests under its consumer, not at the root.
    expect(out.packages['packages/consumer/node_modules/is-number']?.version).toBe('7.0.0')
    expect(codes).not.toContain('YARN_CLASSIC_WORKSPACE_MEMBER_DEPS_UNSYNTHESISED')
  })
})

// A yarn `resolutions` pin can force a version the declared range does NOT satisfy
// (e.g. root declares csstype `^3.1.3` but resolutions pin `3.0.9`). yarn-classic
// root-edge synthesis in `enrich` must honour that pin, not just semver: with ≥2
// same-name candidates and no version the range satisfies, semver has no unique
// target, so only the captured overrides can bind the edge to the pinned node —
// otherwise the root edge is dropped and the dependency vanishes from the output.
describe('yarn-classic root resolution honours a non-satisfying resolutions pin', () => {
  const YARN = `# yarn lockfile v1
csstype@3.0.9:
  version "3.0.9"
  resolved "https://registry.yarnpkg.com/csstype/-/csstype-3.0.9.tgz#aaaa"
  integrity sha512-AAAA
"csstype@^2.5.2":
  version "2.6.21"
  resolved "https://registry.yarnpkg.com/csstype/-/csstype-2.6.21.tgz#bbbb"
  integrity sha512-BBBB
`
  // `^3.1.3` is satisfied by NEITHER 3.0.9 nor 2.6.21; the resolutions pin forces
  // 3.0.9. Two candidates + no satisfier ⇒ only the override map can bridge it.
  const MAN: Record<string, Manifest> = {
    '': {
      name: 'root', version: '1.0.0',
      dependencies: { csstype: '^3.1.3' },
      native: { yarnResolutions: { 'csstype@^3.1.3': '3.0.9' } },
    },
  }

  it('binds the root edge to the pinned csstype 3.0.9 node (not dropped)', () => {
    const g = parse('yarn-classic', YARN, { manifests: MAN })
    expect(g.out('root@1.0.0').map(e => e.dst)).toEqual(['csstype@3.0.9'])
  })

  it('convert → npm-3 keeps the csstype dependency and its pinned node', async () => {
    const npm = JSON.parse(await convert(YARN, { from: 'yarn-classic', to: 'npm-3', manifests: MAN, strict: false })) as {
      packages: Record<string, { dependencies?: Record<string, string> }>
    }
    expect(npm.packages['']?.dependencies).toEqual({ csstype: '^3.1.3' })
    expect('node_modules/csstype' in npm.packages).toBe(true)
  })
})
