import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path, { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import {
  check,
  convert,
  type ConvertFileSystem,
  type Diagnostic,
  type Manifest,
} from '../../main/ts/index.ts'
import { globSegmentRegExp, matchesGlobSet } from '../../main/ts/convert/glob.ts'
import type { Packument, RegistryAdapter } from '../../main/ts/registry/types.ts'

const here = dirname(fileURLToPath(import.meta.url))
const fixture = (relative: string): string => readFileSync(
  resolve(here, '../resources/fixtures/lockfiles', relative),
  'utf8',
)

const NPM = fixture('simple/npm-3.lock')
const DENO = fixture('simple/deno.lock')
const PNPM = fixture('simple/pnpm-v9.lock')
const BERRY_PATCH = fixture('patch-yarn/yarn-berry-v9.lock')
const CLASSIC = `# yarn lockfile v1
foo@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz"
  dependencies:
    bar "^1.0.0"
`
const BERRY_BUILTIN = `# This file is generated by running "yarn install" inside your project.
__metadata:
  version: 8
  cacheKey: 10c0

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    typescript: "patch:typescript@npm%3A5.4.5#~builtin<compat/typescript>"
  languageName: unknown
  linkType: soft

"typescript@npm:5.4.5":
  version: 5.4.5
  resolution: "typescript@npm:5.4.5"
  languageName: node
  linkType: hard

"typescript@patch:typescript@npm%3A5.4.5#~builtin<compat/typescript>::version=5.4.5&hash=14eedb":
  version: 5.4.5
  resolution: "typescript@patch:typescript@npm%3A5.4.5#~builtin<compat/typescript>::version=5.4.5&hash=14eedb"
  languageName: node
  linkType: hard
`

function missing(candidate: string): NodeJS.ErrnoException {
  const error = new Error(`ENOENT: ${candidate}`) as NodeJS.ErrnoException
  error.code = 'ENOENT'
  return error
}

interface MemoryFileSystem {
  readonly fs: ConvertFileSystem
  readonly reads: string[]
  readonly globs: Array<{ readonly cwd: string; readonly patterns: readonly string[] }>
  readonly realpaths: string[]
}

function memoryFileSystem(
  files: Readonly<Record<string, string | Uint8Array>>,
  redirects: Readonly<Record<string, string>> = {},
): MemoryFileSystem {
  const entries = new Map(Object.entries(files).map(([candidate, content]) => [
    path.posix.normalize(candidate),
    content,
  ]))
  const reads: string[] = []
  const globs: Array<{ readonly cwd: string; readonly patterns: readonly string[] }> = []
  const realpaths: string[] = []
  return {
    reads,
    globs,
    realpaths,
    fs: {
      async readFile(candidate) {
        const normalized = path.posix.normalize(candidate)
        reads.push(normalized)
        const content = entries.get(normalized)
        if (content === undefined) throw missing(normalized)
        return content
      },
      async glob(patterns, options) {
        globs.push({ cwd: options.cwd, patterns: [...patterns] })
        return [...entries.keys()].filter(candidate => {
          const relative = path.posix.relative(options.cwd, candidate)
          return relative !== ''
            && !relative.startsWith('../')
            && matchesGlobSet(relative, patterns)
        }).sort()
      },
      async realpath(candidate) {
        const normalized = path.posix.normalize(candidate)
        realpaths.push(normalized)
        return redirects[normalized] ?? normalized
      },
    },
  }
}

const inaccessibleFileSystem: ConvertFileSystem = {
  readFile: async () => { throw new Error('filesystem access is forbidden') },
  glob: async () => { throw new Error('filesystem access is forbidden') },
  realpath: async () => { throw new Error('filesystem access is forbidden') },
}

describe('convert input normalization', () => {
  it('allows byte-exact same-format deno conversion', async () => {
    await expect(convert(DENO, {
      from: 'deno',
      to: 'deno',
      strict: false,
    })).resolves.toBe(DENO)
  })

  it('fails closed on every cross-format deno conversion direction', async () => {
    await expect(convert(DENO, { from: 'deno', to: 'npm-3', strict: false }))
      .rejects.toMatchObject({
        code: 'CAPABILITY_LACK',
        message: expect.stringContaining('https://github.com/denoland/dnt'),
      })
    await expect(convert(NPM, { from: 'npm-3', to: 'deno', strict: false }))
      .rejects.toMatchObject({
        code: 'CAPABILITY_LACK',
        message: expect.stringContaining('https://github.com/denoland/dnt'),
      })
  })

  it('treats a bare string as lockfile content and never as a path', async () => {
    await expect(convert('package-lock.json', {
      to: 'npm-3',
      fs: inaccessibleFileSystem,
    })).rejects.toMatchObject({ code: 'FORMAT_DETECT_FAILED' })
  })

  it('keeps ProjectInput conversion filesystem-independent', async () => {
    const expected = await convert(NPM, { to: 'pnpm-v9', strict: false })
    const actual = await convert({ files: { 'package-lock.json': NPM } }, {
      to: 'pnpm-v9',
      strict: false,
      fs: inaccessibleFileSystem,
    })

    expect(actual).toBe(expected)
  })

  it('reads ProjectPathInput only through the supplied filesystem seam', async () => {
    const memory = memoryFileSystem({ '/repo/package-lock.json': NPM })
    const expected = await convert({ files: { 'package-lock.json': NPM } }, { to: 'pnpm-v9', strict: false })
    const actual = await convert({ cwd: '/repo', patterns: ['package-lock.json'] }, {
      to: 'pnpm-v9',
      strict: false,
      fs: memory.fs,
    })

    expect(actual).toBe(expected)
    expect(memory.globs).toContainEqual({ cwd: '/repo', patterns: ['package-lock.json'] })
    expect(memory.reads).toContain('/repo/package-lock.json')
  })

  it('uses the default Node filesystem for ProjectPathInput', async () => {
    const root = mkdtempSync(path.join(tmpdir(), 'lockgraph-convert-'))
    try {
      writeFileSync(path.join(root, 'package-lock.json'), NPM)
      const output = await convert({ cwd: root, patterns: ['package-lock.json'] }, { to: 'pnpm-v9', strict: false })
      expect(check('pnpm-v9', output)).toBe(true)
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  it('rejects zero or multiple supported lockfiles', async () => {
    await expect(convert({ files: { 'package.json': '{}' } }, { to: 'npm-3' }))
      .rejects.toMatchObject({ code: 'FORMAT_DETECT_FAILED' })
    await expect(convert({
      files: {
        'package-lock.json': NPM,
        'yarn.lock': '# yarn lockfile v1\n',
      },
    }, { to: 'npm-3' })).rejects.toMatchObject({ code: 'INVALID_INPUT' })
  })

  it('rejects filename/content and explicit-source mismatches', async () => {
    await expect(convert({ files: { 'yarn.lock': NPM } }, { to: 'npm-3' }))
      .rejects.toMatchObject({ code: 'FORMAT_MISMATCH' })
    await expect(convert({ files: { 'package-lock.json': NPM } }, {
      from: 'yarn-classic',
      to: 'npm-3',
    })).rejects.toMatchObject({ code: 'FORMAT_MISMATCH' })
  })

  it.each([
    '../package-lock.json',
    'nested/../package-lock.json',
    '/tmp/package-lock.json',
    'C:/package-lock.json',
    'nested\\package-lock.json',
    'package-lock.json\0suffix',
  ])('rejects unsafe ProjectInput key %j', async candidate => {
    await expect(convert({ files: { [candidate]: NPM } }, { to: 'npm-3' }))
      .rejects.toMatchObject({ code: 'INVALID_INPUT' })
  })

  it('rejects ProjectInput keys that collide after normalization', async () => {
    await expect(convert({
      files: {
        './package-lock.json': NPM,
        'package-lock.json': NPM,
      },
    }, { to: 'npm-3' })).rejects.toMatchObject({ code: 'INVALID_INPUT' })
  })

  it('rejects invalid UTF-8 in lockfiles, manifests, and text configs', async () => {
    const invalid = Uint8Array.of(0xff)
    await expect(convert({ files: { 'package-lock.json': invalid } }, { to: 'npm-3' }))
      .rejects.toMatchObject({ code: 'INVALID_INPUT' })
    await expect(convert({ files: { 'package-lock.json': NPM, 'package.json': invalid } }, { to: 'npm-3' }))
      .rejects.toMatchObject({ code: 'INVALID_INPUT' })
    await expect(convert({ files: { 'package-lock.json': NPM, '.npmrc': invalid } }, { to: 'npm-3' }))
      .rejects.toMatchObject({ code: 'INVALID_INPUT' })
  })

  it('rejects a path match whose realpath escapes the search root', async () => {
    const memory = memoryFileSystem(
      { '/repo/package-lock.json': NPM },
      { '/repo/package-lock.json': '/outside/package-lock.json' },
    )

    await expect(convert({ cwd: '/repo', patterns: ['package-lock.json'] }, {
      to: 'npm-3',
      fs: memory.fs,
    })).rejects.toMatchObject({ code: 'INVALID_INPUT' })
  })

  it('rejects brace expansion beyond the bounded result limit', async () => {
    const braceBomb = `${'{a,b}/'.repeat(9)}package`
    await expect(convert({
      files: {
        'package-lock.json': NPM,
        'package.json': JSON.stringify({ workspaces: [braceBomb] }),
      },
    }, { to: 'npm-3' })).rejects.toMatchObject({ code: 'INVALID_INPUT' })
  })

  it('collapses adjacent stars before matching an adversarial segment', async () => {
    const segment = `p${'*'.repeat(4096)}z`
    const candidate = `p${'a'.repeat(4096)}y`
    const matcher = globSegmentRegExp(segment)
    expect(matcher.source.split('[^/]*')).toHaveLength(2)
    expect(matcher.test(candidate)).toBe(false)

    await expect(convert({
      files: {
        'package-lock.json': NPM,
        'package.json': JSON.stringify({ workspaces: [segment] }),
        [`${candidate}/package.json`]: JSON.stringify({ name: 'candidate', version: '1.0.0' }),
      },
    }, { to: 'lockgraph', strict: false })).resolves.toEqual(expect.any(String))
  })

  it('rejects traversal introduced by brace expansion', async () => {
    await expect(convert({
      files: {
        'package-lock.json': NPM,
        'package.json': JSON.stringify({ workspaces: ['{packages,..}/x'] }),
      },
    }, { to: 'npm-3' })).rejects.toMatchObject({ code: 'INVALID_INPUT' })
  })
})

describe('convert project facts', () => {
  it('discovers nested workspace manifests relative to each declaring manifest', async () => {
    const memory = memoryFileSystem({
      '/repo/yarn.lock': CLASSIC,
      '/repo/package.json': JSON.stringify({
        name: 'root',
        version: '1.0.0',
        dependencies: { foo: '^1.0.0' },
        workspaces: ['packages/*'],
      }),
      '/repo/packages/a/package.json': JSON.stringify({
        name: '@ws/a',
        version: '1.0.0',
        dependencies: { foo: '^1.0.0' },
        workspaces: ['nested/*'],
      }),
      '/repo/packages/a/nested/b/package.json': JSON.stringify({
        name: '@ws/b',
        version: '1.0.0',
      }),
    })
    const output = JSON.parse(await convert({ cwd: '/repo', patterns: ['yarn.lock'] }, {
      to: 'npm-3',
      strict: false,
      fs: memory.fs,
    })) as { packages: Record<string, { name?: string }> }

    expect(memory.globs).toContainEqual({
      cwd: '/repo/packages/a',
      patterns: ['nested/*/package.json'],
    })
    expect(Object.keys(output.packages)).toEqual(expect.arrayContaining([
      'packages/a',
      'packages/a/nested/b',
    ]))
  })

  it('discovers pnpm members from the root workspace config', async () => {
    const diagnostics: Diagnostic[] = []
    const memory = memoryFileSystem({
      '/repo/pnpm-lock.yaml': PNPM,
      '/repo/pnpm-workspace.yaml': "packages:\n  - 'packages/*'\n",
      '/repo/packages/a/package.json': JSON.stringify({ name: '@ws/a', version: '1.0.0' }),
    })
    await convert({ cwd: '/repo', patterns: ['pnpm-lock.yaml'] }, {
      to: 'lockgraph',
      strict: false,
      fs: memory.fs,
      onDiagnostic: diagnostic => diagnostics.push(diagnostic),
    })

    expect(memory.globs).toContainEqual({
      cwd: '/repo',
      patterns: ['packages/*/package.json'],
    })
    expect(diagnostics.map(item => item.code)).not.toContain('CONVERT_WORKSPACE_MANIFEST_MISSING')
  })

  it('reports each unmatched positive workspace pattern independently', async () => {
    const diagnostics: Diagnostic[] = []
    await convert({
      files: {
        'package-lock.json': NPM,
        'package.json': JSON.stringify({
          name: 'case-simple',
          version: '0.0.0',
          workspaces: ['packages/*', 'apps/*'],
        }),
        'packages/a/package.json': JSON.stringify({ name: '@ws/a', version: '1.0.0' }),
      },
    }, {
      to: 'npm-3',
      strict: false,
      onDiagnostic: diagnostic => diagnostics.push(diagnostic),
    })

    const missing = diagnostics.filter(item => item.code === 'CONVERT_WORKSPACE_MANIFEST_MISSING')
    expect(missing).toHaveLength(1)
    expect(missing[0]?.data?.pattern).toBe('apps/*/package.json')
  })

  it('coalesces structurally equal manifests and rejects conflicts', async () => {
    const manifest: Manifest = {
      dependencies: { ms: '2.1.3', lodash: '4.17.21' },
      version: '0.0.0',
      name: 'case-simple',
    }
    const project = {
      files: {
        'package-lock.json': NPM,
        'package.json': JSON.stringify({
          name: 'case-simple',
          version: '0.0.0',
          dependencies: { lodash: '4.17.21', ms: '2.1.3' },
        }, null, 2),
      },
    }

    const output = await convert(project, { to: 'npm-3', manifests: { '': manifest }, strict: false })
    expect(check('npm-3', output)).toBe(true)
    await expect(convert(project, {
      to: 'npm-3',
      manifests: { '': { ...manifest, name: 'conflict' } },
    })).rejects.toMatchObject({ code: 'INVALID_INPUT' })
  })

  it('coalesces equivalent native and canonical override manifests', async () => {
    const manifest = {
      name: 'root',
      version: '1.0.0',
      dependencies: { foo: '^1.0.0' },
    }
    const output = await convert({
      files: {
        'yarn.lock': CLASSIC,
        'package.json': JSON.stringify({
          ...manifest,
          resolutions: { bar: '1.5.0' },
        }),
      },
    }, {
      to: 'npm-3',
      strict: false,
      manifests: {
        '': {
          ...manifest,
          native: { yarnResolutions: { bar: '1.5.0' } },
        },
      },
    })

    expect(check('npm-3', output)).toBe(true)
  })

  it('routes explicit manifest and registry sources through snapshot enrichment', async () => {
    const calls: string[] = []
    const registry: RegistryAdapter = {
      async packument(name): Promise<Packument | undefined> {
        return name === 'foo'
          ? {
              name: 'foo',
              distTags: { latest: '1.0.0' },
              versions: {
                '1.0.0': {
                  name: 'foo',
                  version: '1.0.0',
                  dependencies: { bar: '^1.0.0' },
                },
              },
            }
          : name === 'bar'
          ? {
              name: 'bar',
              distTags: { latest: '1.5.0' },
              versions: { '1.5.0': { name: 'bar', version: '1.5.0' } },
            }
          : undefined
      },
      async resolve(name, range) {
        calls.push(`${name}@${range}`)
        return name === 'bar' && range === '^1.0.0'
          ? { name: 'bar', version: '1.5.0' }
          : undefined
      },
    }
    const output = JSON.parse(await convert({ files: { 'yarn.lock': CLASSIC } }, {
      to: 'npm-3',
      strict: false,
      sources: {
        manifests: {
          '': {
            name: 'root',
            version: '1.0.0',
            dependencies: { foo: '^1.0.0' },
            overrides: [],
          },
        },
        registry,
      },
    })) as { packages: Record<string, { version?: string }> }

    expect(calls).toContain('bar@^1.0.0')
    expect(Object.values(output.packages).some(pkg => pkg.version === '1.5.0')).toBe(true)
  })

  it('diagnoses unresolved Berry file-backed patches in path mode', async () => {
    const diagnostics: Diagnostic[] = []
    const memory = memoryFileSystem({ '/repo/yarn.lock': BERRY_PATCH })
    const output = await convert({ cwd: '/repo', patterns: ['yarn.lock'] }, {
      to: 'lockgraph',
      strict: false,
      fs: memory.fs,
      onDiagnostic: diagnostic => diagnostics.push(diagnostic),
    })

    expect(output).toContain('unresolved-')
    expect(diagnostics).toContainEqual(expect.objectContaining({
      code: 'CONVERT_PATCH_BYTES_UNAVAILABLE',
      severity: 'warning',
      data: expect.objectContaining({
        patchPath: expect.stringContaining('.yarn/patches/'),
        reason: 'path-fs-seam-not-threaded',
        remedy: 'pass-workspaceRoot',
      }),
    }))
  })

  it('diagnoses unresolved Berry file-backed patches in project mode', async () => {
    const diagnostics: Diagnostic[] = []
    const output = await convert({ files: { 'yarn.lock': BERRY_PATCH } }, {
      to: 'lockgraph',
      strict: false,
      onDiagnostic: diagnostic => diagnostics.push(diagnostic),
    })

    expect(output).toContain('unresolved-')
    expect(diagnostics).toContainEqual(expect.objectContaining({
      code: 'CONVERT_PATCH_BYTES_UNAVAILABLE',
      data: expect.objectContaining({
        reason: 'project-input-has-no-patch-byte-channel',
        remedy: 'pass-workspaceRoot',
      }),
    }))
  })

  it('diagnoses unresolved Berry file-backed patches in content mode', async () => {
    const diagnostics: Diagnostic[] = []
    await convert(BERRY_PATCH, {
      to: 'lockgraph',
      strict: false,
      onDiagnostic: diagnostic => diagnostics.push(diagnostic),
    })

    expect(diagnostics).toContainEqual(expect.objectContaining({
      code: 'CONVERT_PATCH_BYTES_UNAVAILABLE',
      data: expect.objectContaining({ reason: 'lock-content-has-no-patch-bytes' }),
    }))
  })

  it('does not report builtin-only Berry patches as missing file bytes', async () => {
    const diagnostics: Diagnostic[] = []
    await convert({ files: { 'yarn.lock': BERRY_BUILTIN } }, {
      to: 'lockgraph',
      strict: false,
      onDiagnostic: diagnostic => diagnostics.push(diagnostic),
    })

    expect(diagnostics.map(item => item.code)).not.toContain('CONVERT_PATCH_BYTES_UNAVAILABLE')
  })
})
