import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import {
  complete,
  modify,
  parse,
  refurbish,
  stringify,
  type FormatId,
  type Diagnostic,
  type NpmTarballSource,
  type PackumentVersion,
  type RegistryAdapter,
} from '../../main/ts/index.ts'
import { LockfileError } from '../../main/ts/api/errors.ts'
import { stringifyProjected } from '../../main/ts/api/format-api.ts'
import {
  isStructuralExpectedDrop,
  projectionPreflightLosses,
} from '../../main/ts/completeness/projection.ts'
import { newBuilder, type Graph, type TarballPayload } from '../../main/ts/graph.ts'
import { rebindAdapterState as rebindPnpmFlatAdapterState } from '../../main/ts/formats/_pnpm-flat-core.ts'
import * as bunText from '../../main/ts/formats/bun-text.ts'
import * as pnpmV5 from '../../main/ts/formats/pnpm-v5.ts'
import * as yarnBerryV9 from '../../main/ts/formats/yarn-berry-v9.ts'
import { emitBerryChecksum, type Integrity } from '../../main/ts/recipe/integrity.ts'
import { rebindAdapterState as rebindNpmFlatAdapterState } from '../../main/ts/formats/_npm-core.ts'

const here = dirname(fileURLToPath(import.meta.url))
const fixture = (file: string): string =>
  readFileSync(resolve(here, '../resources/fixtures/lockfiles/simple', file), 'utf8')
const npm4ExtensionFixture = (): string =>
  readFileSync(resolve(here, '../resources/fixtures/npm-v4/npm-extension/package-lock.json'), 'utf8')

/** Producer-authored `yarn install` output for a project whose only dependency
 * is `optionalDependencies: { fsevents: "2.3.3" }` — Yarn 3.6.4 (lock v6) and
 * Yarn 4.13.0 (lock v8). Both carry a conditioned builtin-compat patch entry
 * that Yarn writes WITHOUT a `checksum`, next to the unpatched archive sibling
 * that keeps one. */
const berryConditionalFixture = (format: 'yarn-berry-v6' | 'yarn-berry-v8'): string =>
  readFileSync(
    resolve(here, '../resources/fixtures/berry-conditional-checksum', `${format}.lock`),
    'utf8',
  )

/** Rewrite one `yarn.lock` entry block in place, addressed by a predicate over
 * its text. Keeps the surrounding bytes verbatim so a strict round-trip still
 * compares against producer output. */
function editBerryEntry(
  text: string,
  matches: (block: string) => boolean,
  edit: (lines: readonly string[]) => string[],
): string {
  const blocks = text.split('\n\n')
  const index = blocks.findIndex(block => block.startsWith('"') && matches(block))
  expect(index).toBeGreaterThanOrEqual(0)
  const next = blocks.slice()
  next[index] = edit(blocks[index]!.split('\n')).join('\n')
  return next.join('\n\n')
}

const withoutChecksumLine = (lines: readonly string[]): string[] =>
  lines.filter(line => !line.startsWith('  checksum:'))

const isPatchedFseventsEntry = (block: string): boolean =>
  block.includes('builtin<compat/fsevents>')
const isArchiveSiblingEntry = (block: string): boolean =>
  block.includes('\n  resolution: "fsevents@npm:')
const isUnconditionedEntry = (block: string): boolean =>
  block.includes('\n  resolution: "graceful-fs@npm:')

/** A checksum-less conditioned package. Reached optionally, Yarn leaves it in
 * `optionalBuilds` and writes no `checksum`; reached through a required path it
 * materialises the package and writes one, so the same absence is a real loss. */
const conditionedLock = (reach: 'optional' | 'required'): string => [
  '# This file is generated by running "yarn install" inside your project.',
  '# Manual changes might be lost - proceed with caution!',
  '',
  '__metadata:',
  '  version: 8',
  '  cacheKey: 10c0',
  '',
  '"cond@npm:1.0.0":',
  '  version: 1.0.0',
  '  resolution: "cond@npm:1.0.0"',
  '  conditions: os=darwin',
  '  languageName: node',
  '  linkType: hard',
  '',
  '"root@workspace:.":',
  '  version: 0.0.0-use.local',
  '  resolution: "root@workspace:."',
  '  dependencies:',
  '    cond: "npm:1.0.0"',
  ...(reach === 'optional' ? ['  dependenciesMeta:', '    cond:', '      optional: true'] : []),
  '  languageName: unknown',
  '  linkType: soft',
  '',
].join('\n')

/** A checksum-free soft-link package exactly as Berry writes it. Directory
 * locators are not archive-backed, regardless of the package version carried
 * by the linked manifest. */
const linkedLock = (version: string): string => [
  '# This file is generated by running "yarn install" inside your project.',
  '# Manual changes might be lost - proceed with caution!',
  '',
  '__metadata:',
  '  version: 8',
  '  cacheKey: 10c0',
  '',
  '"root@workspace:.":',
  '  version: 0.0.0-use.local',
  '  resolution: "root@workspace:."',
  '  dependencies:',
  '    ui: "link:./src/ui"',
  '  languageName: unknown',
  '  linkType: soft',
  '',
  '"ui@link:./src/ui::locator=root%40workspace%3A.":',
  `  version: ${version}`,
  '  resolution: "ui@link:./src/ui::locator=root%40workspace%3A."',
  '  languageName: node',
  '  linkType: soft',
  '',
].join('\n')

/** Berry v8 also accepts a bare checksum even though newly-created entries use
 * the metadata cache key prefix. Parsed source spelling remains authoritative. */
const bareChecksumLock = (): string => [
  '# This file is generated by running "yarn install" inside your project.',
  '# Manual changes might be lost - proceed with caution!',
  '',
  '__metadata:',
  '  version: 8',
  '  cacheKey: 10c0',
  '',
  '"dep@npm:1.0.0":',
  '  version: 1.0.0',
  '  resolution: "dep@npm:1.0.0"',
  `  checksum: ${'ab'.repeat(64)}`,
  '  languageName: node',
  '  linkType: hard',
  '',
  '"root@workspace:.":',
  '  version: 0.0.0-use.local',
  '  resolution: "root@workspace:."',
  '  dependencies:',
  '    dep: "npm:1.0.0"',
  '  languageName: unknown',
  '  linkType: soft',
  '',
].join('\n')

const sriIntegrity: Integrity = {
  hashes: [{ algorithm: 'sha512', digest: 'ab'.repeat(64), origin: 'sri' }],
}

const berryIntegrity: Integrity = {
  hashes: [{ algorithm: 'sha512', digest: 'cd'.repeat(64), origin: 'berry-zip' }],
}

function metadataGraph(integrity: Integrity = sriIntegrity): Graph {
  const builder = newBuilder()
  builder.addNode({
    id: 'project@0.0.0',
    name: 'project',
    version: '0.0.0',
    peerContext: [],
    workspacePath: '',
  })
  builder.addNode({ id: 'dep@1.0.0', name: 'dep', version: '1.0.0', peerContext: [] })
  builder.addEdge('project@0.0.0', 'dep@1.0.0', 'dep', { range: '1.0.0' })
  builder.setTarball({ name: 'dep', version: '1.0.0' }, {
    integrity: { hashes: [...integrity.hashes] },
    funding: { url: 'https://example.test/fund' },
    license: 'MIT',
    peerDependencies: { peer: '^1.0.0' },
    peerDependenciesMeta: { peer: { optional: true } },
    resolution: { type: 'tarball', url: 'https://registry.example/dep/-/dep-1.0.0.tgz' },
  })
  return builder.seal()
}

function singleMetadataGraph(
  metadata: Partial<TarballPayload>,
  integrity: Integrity = sriIntegrity,
  targetShape?: 'yarn-classic' | 'yarn-berry-v8',
): Graph {
  const builder = newBuilder()
  builder.addNode({
    id: 'project@0.0.0',
    name: 'project',
    version: '0.0.0',
    peerContext: [],
    ...(targetShape === 'yarn-classic' ? {} : { workspacePath: '' }),
  })
  builder.addNode({ id: 'dep@1.0.0', name: 'dep', version: '1.0.0', peerContext: [] })
  builder.addEdge('project@0.0.0', 'dep@1.0.0', 'dep', {
    range: '1.0.0',
  })
  builder.setTarball({ name: 'dep', version: '1.0.0' }, {
    integrity: { hashes: [...integrity.hashes] },
    ...(targetShape === 'yarn-berry-v8' ? { berryChecksumCacheKey: '10c0' } : {}),
    resolution: { type: 'tarball', url: 'https://registry.npmjs.org/dep/-/dep-1.0.0.tgz' },
    ...metadata,
  })
  return builder.seal()
}

function peerContextGraph(): Graph {
  const builder = newBuilder()
  builder.addNode({
    id: 'project@0.0.0',
    name: 'project',
    version: '0.0.0',
    peerContext: [],
    workspacePath: '',
  })
  builder.addNode({ id: 'peer@1.0.0', name: 'peer', version: '1.0.0', peerContext: [] })
  builder.addNode({
    id: 'consumer@1.0.0(peer@1.0.0)',
    name: 'consumer',
    version: '1.0.0',
    peerContext: ['peer@1.0.0'],
  })
  builder.addEdge('project@0.0.0', 'consumer@1.0.0(peer@1.0.0)', 'dep', { range: '1.0.0' })
  builder.addEdge('consumer@1.0.0(peer@1.0.0)', 'peer@1.0.0', 'peer', { range: '^1.0.0' })
  for (const name of ['peer', 'consumer']) {
    builder.setTarball({ name, version: '1.0.0' }, {
      integrity: { hashes: [...sriIntegrity.hashes] },
      resolution: { type: 'tarball', url: `https://registry.example/${name}/-/${name}-1.0.0.tgz` },
    })
  }
  return builder.seal()
}

function caught(format: FormatId, graph: Graph): LockfileError {
  try {
    stringify(format, graph)
  } catch (error) {
    expect(error).toBeInstanceOf(LockfileError)
    return error as LockfileError
  }
  throw new Error(`expected strict ${format} stringify to reject a projection loss`)
}

type MetadataRefusalTarget = 'bun-text' | 'pnpm-v5' | 'pnpm-v6' | 'pnpm-v9'
type SriProjectionTarget = 'npm-3' | 'pnpm-v9' | 'bun-text'

function addMetadataToNativeControl(
  format: MetadataRefusalTarget,
  control: Graph,
  metadata: Partial<TarballPayload>,
): Graph {
  const node = [...control.nodes()].find(candidate => candidate.name === 'lodash')
  expect(node).toBeDefined()
  const payload = control.tarballOf(node!.id)
  expect(payload).toBeDefined()
  const mutated = control.mutate(mutable => {
    mutable.setTarball({ name: node!.name, version: node!.version }, {
      ...payload,
      ...metadata,
    })
  }).graph

  if (format === 'bun-text') return bunText.rebindAdapterState(control, mutated).graph
  if (format === 'pnpm-v5') return pnpmV5.rebindAdapterState(control, mutated).graph
  return rebindPnpmFlatAdapterState(control, mutated).graph
}

function addBerryIntegrityToNativeControl(
  format: SriProjectionTarget,
  control: Graph,
): Graph {
  const node = [...control.nodes()].find(candidate => candidate.name === 'lodash')
  expect(node).toBeDefined()
  const payload = control.tarballOf(node!.id)
  expect(payload?.integrity).toBeDefined()
  const mutated = control.mutate(mutable => {
    mutable.setTarball({ name: node!.name, version: node!.version }, {
      ...payload,
      berryChecksumCacheKey: '10c0',
      integrity: {
        hashes: [...payload!.integrity!.hashes, ...berryIntegrity.hashes],
      },
    })
  }).graph
  if (format === 'npm-3') return rebindNpmFlatAdapterState(control, mutated).graph
  if (format === 'bun-text') return bunText.rebindAdapterState(control, mutated).graph
  return rebindPnpmFlatAdapterState(control, mutated).graph
}

async function completedBerryIntegrityGraph() {
  const bytes = readFileSync(resolve(
    here,
    '../resources/fixtures/tarballs/ms-2.1.3.tgz',
  ))
  const registryIntegrity: Integrity = {
    hashes: [{
      algorithm: 'sha512',
      digest: createHash('sha512').update(bytes).digest('hex'),
      origin: 'sri',
    }],
  }
  const versions: Record<string, PackumentVersion> = {
    ms: { name: 'ms', version: '2.1.3', dependencies: { vuln: '2.0.0' } },
    vuln: {
      name: 'vuln',
      version: '2.0.0',
      integrity: registryIntegrity,
      tarball: 'https://registry.npmjs.org/vuln/-/vuln-2.0.0.tgz',
    },
  }
  const registry: RegistryAdapter = {
    async packument(name) {
      const version = versions[name]
      return version === undefined
        ? undefined
        : { name, distTags: {}, versions: { [version.version]: version } }
    },
    async resolve(name) { return versions[name] },
  }
  const completed = await complete(parse(fixture('yarn-berry-v8.lock'), 'yarn-berry-v8'), {
    target: 'yarn-berry-v8',
    sources: { packuments: [registry] },
  })
  return { bytes, completed, registryDigest: registryIntegrity.hashes[0]!.digest }
}

async function yafMultiOriginIntegrityGraph() {
  const bytes = readFileSync(resolve(
    here,
    '../resources/fixtures/tarballs/ms-2.1.3.tgz',
  ))
  const sri = `sha512-${Buffer.alloc(64, 7).toString('base64')}`
  const shasum = 'a'.repeat(40)
  const tarball = `https://registry.npmjs.org/vuln/-/vuln-2.0.0.tgz#${shasum}`
  const version = {
    name: 'vuln',
    version: '2.0.0',
    dependencies: {},
    dist: { integrity: sri, shasum, tarball },
    integrity: sri,
    tarball,
  } as unknown as PackumentVersion
  const registry: RegistryAdapter = {
    async packument(name) {
      return name === 'vuln'
        ? { name, distTags: { latest: '2.0.0' }, versions: { '2.0.0': version } }
        : undefined
    },
    async resolve(name) { return name === 'vuln' ? version : undefined },
  }
  const source = parse(
    '__metadata:\n' +
    '  version: 8\n' +
    '  cacheKey: 10c0\n\n' +
    '"root@workspace:.":\n' +
    '  version: 0.0.0-use.local\n' +
    '  resolution: "root@workspace:."\n' +
    '  dependencies:\n' +
    '    vuln: "npm:1.0.0"\n' +
    '  languageName: unknown\n' +
    '  linkType: soft\n\n' +
    '"vuln@npm:1.0.0":\n' +
    '  version: 1.0.0\n' +
    '  resolution: "vuln@npm:1.0.0"\n' +
    `  checksum: 10c0/${'a'.repeat(128)}\n` +
    '  languageName: node\n' +
    '  linkType: hard\n',
    'yarn-berry-v8',
  )
  const modified = await modify(source, {
    kind: 'replaceVersion',
    selector: { name: 'vuln', fromRange: '<2.0.0' },
    to: '2.0.0',
  }, {
    target: 'yarn-berry-v8',
    sources: { packuments: [registry] },
  })
  const completed = await complete(modified.graph, {
    target: 'yarn-berry-v8',
    sources: { packuments: [registry] },
    seed: modified.frontier,
    pruneOrphans: true,
  })
  return {
    bytes,
    completed,
    registryDigest: Buffer.alloc(64, 7).toString('hex'),
  }
}

describe('strict projection gate', () => {
  it('reports and strict-rejects npm-4 manifest-extension provenance loss', () => {
    const graph = parse('npm-4', npm4ExtensionFixture())
    const projected = stringifyProjected('npm-3', graph)

    expect(projected.losses).toContainEqual(expect.objectContaining({
      class: 'inherent-meaningful',
      feature: 'manifest-extension-provenance',
      target: 'npm-3',
    }))
    expect(projected.diagnostics).toContainEqual(expect.objectContaining({
      code: 'PROJECTION_LOSS',
      data: expect.objectContaining({
        class: 'inherent-meaningful',
        feature: 'manifest-extension-provenance',
        target: 'npm-3',
      }),
    }))

    const error = caught('npm-3', graph)
    expect(error.code).toBe('IRREDUCIBLE_LOSS')
    expect(() => stringify('npm-4', graph)).not.toThrow()
  })

  it.each([
    ['yarn-classic', sriIntegrity],
    ['yarn-berry-v8', berryIntegrity],
  ] as const)('%s accepts an allowlisted engines drop and reports it', (format, integrity) => {
    const graph = singleMetadataGraph({ engines: { node: '>=18' } }, integrity, format)
    const projected = stringifyProjected(format, graph)

    expect(projected.losses).toEqual(expect.arrayContaining([
      expect.objectContaining({
        class: 'structural-expected',
        feature: 'metadata:engines',
        target: format,
      }),
    ]))
    expect(() => stringify(format, graph)).not.toThrow()
    expect(projected.diagnostics.some(diagnostic =>
      diagnostic.code === 'PROJECTION_LOSS'
        && diagnostic.data?.class === 'structural-expected')).toBe(true)
  })

  it('accepts a metadata-only node whose payload projects to empty (CASE-A)', () => {
    // A completed transitive carrying ONLY engines (no integrity/resolution): its yarn-classic
    // tarball payload projects to `{}`, and the reparse emits no entry for it. The output-graph
    // snapshot must omit the empty-after-projection payload, not diff `{}` against absent.
    const builder = newBuilder()
    builder.addNode({ id: 'project@0.0.0', name: 'project', version: '0.0.0', peerContext: [] })
    builder.addNode({ id: 'dep@1.0.0', name: 'dep', version: '1.0.0', peerContext: [] })
    builder.addEdge('project@0.0.0', 'dep@1.0.0', 'dep', { range: '1.0.0' })
    builder.setTarball({ name: 'dep', version: '1.0.0' }, { engines: { node: '>=20' } })
    expect(() => stringify('yarn-classic', builder.seal())).not.toThrow()
  })

  it.each([
    ['funding', { url: 'https://example.test/fund' }],
    ['license', 'MIT'],
  ] as const)('accepts a metadata-only %s field Yarn structurally omits', (field, value) => {
    const builder = newBuilder()
    builder.addNode({ id: 'project@0.0.0', name: 'project', version: '0.0.0', peerContext: [] })
    builder.addNode({ id: 'dep@1.0.0', name: 'dep', version: '1.0.0', peerContext: [] })
    builder.addEdge('project@0.0.0', 'dep@1.0.0', 'dep', { range: '1.0.0' })
    builder.setTarball({ name: 'dep', version: '1.0.0' }, { [field]: value })
    const graph = builder.seal()
    expect(stringifyProjected('yarn-classic', graph).losses).toContainEqual(
      expect.objectContaining({
        class: 'structural-expected',
        feature: `metadata:${field}`,
      }),
    )
    expect(() => stringify('yarn-classic', graph)).not.toThrow()
  })

  it('keeps the structural allowlist pair-specific', () => {
    const graph = singleMetadataGraph({
      engines: { node: '>=18' },
      deprecated: 'use dep-next',
      bin: { dep: 'cli.js' },
      funding: { url: 'https://example.test/fund' },
      license: 'MIT',
    }, sriIntegrity, 'yarn-classic')
    const classic = stringifyProjected('yarn-classic', graph)
    expect(classic.losses.map(loss => [loss.class, loss.feature])).toEqual([
      ['structural-expected', 'metadata:bin'],
      ['structural-expected', 'metadata:deprecated'],
      ['structural-expected', 'metadata:engines'],
      ['structural-expected', 'metadata:funding'],
      ['structural-expected', 'metadata:license'],
    ])

    const pnpm = caught('pnpm-v9', graph)
    expect(pnpm.losses).toEqual(expect.arrayContaining([
      expect.objectContaining({ class: 'inherent-meaningful', feature: 'metadata:funding' }),
      expect.objectContaining({ class: 'inherent-meaningful', feature: 'metadata:license' }),
    ]))
    expect(isStructuralExpectedDrop('bin', 'pnpm-v9')).toBe(false)

    for (const field of [
      'cpu',
      'os',
      'libc',
      'hasInstallScript',
      'bundledDependencies',
    ] as const) {
      expect(isStructuralExpectedDrop(field, 'yarn-classic')).toBe(false)
    }
  })

  it('strict-passes the bun native control before refusing minted storage metadata', () => {
    const control = parse('bun-text', fixture('bun-text.lock'))
    expect(() => stringify('bun-text', control)).not.toThrow()

    const withMetadata = addMetadataToNativeControl('bun-text', control, {
      os: ['linux'],
      cpu: ['x64'],
      bin: { lodash: 'cli.js' },
      peerDependencies: { peer: '^1.0.0' },
    })
    const error = caught('bun-text', withMetadata)
    expect(error.code).toBe('IRREDUCIBLE_LOSS')
    expect(error.losses).toContainEqual(expect.objectContaining({
      class: 'inherent-meaningful',
      feature: 'completeness-output-graph-mismatch',
      diagnostic: expect.objectContaining({ code: 'COMPLETENESS_OUTPUT_GRAPH_MISMATCH' }),
    }))
    expect(error.losses?.some(loss => loss.feature.startsWith('metadata:'))).toBe(false)
  })

  it.each([
    ['pnpm-v5', 'pnpm-v5.lock'],
    ['pnpm-v6', 'pnpm-v6.lock'],
    ['pnpm-v9', 'pnpm-v9.lock'],
  ] as const)('strict-passes the %s native control before refusing minted bin metadata', (format, file) => {
    const control = parse(format, fixture(file))
    expect(() => stringify(format, control)).not.toThrow()

    const withMetadata = addMetadataToNativeControl(format, control, {
      bin: { lodash: 'cli.js' },
    })
    const error = caught(format, withMetadata)
    expect(error.code).toBe('IRREDUCIBLE_LOSS')
    expect(error.losses).toContainEqual(expect.objectContaining({
      class: 'inherent-meaningful',
      feature: 'completeness-output-graph-mismatch',
      diagnostic: expect.objectContaining({ code: 'COMPLETENESS_OUTPUT_GRAPH_MISMATCH' }),
    }))
    expect(error.losses?.some(loss => loss.feature === 'metadata:bin')).toBe(false)
  })

  it('still rejects platform metadata with no source Berry attribution', () => {
    const error = caught(
      'yarn-berry-v8',
      singleMetadataGraph(
        { os: ['linux'], cpu: ['x64'] },
        berryIntegrity,
        'yarn-berry-v8',
      ),
    )
    expect(error.code).toBe('IRREDUCIBLE_LOSS')
    expect(error.losses?.some(loss =>
      loss.feature === 'conditions'
        && loss.diagnostic.code === 'COMPLETENESS_OUTPUT_FEATURE_MISMATCH')).toBe(true)
    expect(error.losses?.some(loss =>
      loss.feature === 'completeness-output-graph-mismatch')).toBe(false)
  })

  it.each([
    'npm-1',
    'pnpm-v5',
    'pnpm-v6',
    'pnpm-v9',
    'bun-text',
  ] as const)('%s rejects a held metadata fact its emitter cannot carry', format => {
    const error = caught(format, metadataGraph())
    expect(error.code).toBe('IRREDUCIBLE_LOSS')
    expect(error.losses?.some(loss => loss.feature === 'metadata:license')).toBe(true)
  })

  it.each([
    ['npm-3', 'npm-3.lock'],
    ['pnpm-v9', 'pnpm-v9.lock'],
    ['bun-text', 'bun-text.lock'],
  ] as const)('%s projects an unexpressible Berry checksum without losing tarball SRI', (format, file) => {
    const control = parse(format, fixture(file))
    expect(() => stringify(format, control)).not.toThrow()
    const graph = addBerryIntegrityToNativeControl(format, control)
    const projected = stringifyProjected(format, graph)

    expect(projected.losses).toContainEqual(expect.objectContaining({
      class: 'structural-expected',
      feature: 'integrity:berry-zip',
      target: format,
    }))
    expect(projected.losses.some(loss =>
      loss.feature === 'completeness-output-graph-mismatch')).toBe(false)
    expect(() => stringify(format, graph)).not.toThrow()
  })

  it.each([
    'yarn-berry-v4',
    'yarn-berry-v5',
    'yarn-berry-v6',
    'yarn-berry-v7',
    'yarn-berry-v8',
    'yarn-berry-v9',
    'yarn-berry-v10',
  ] as const)('%s accepts structurally omitted funding/license with a valid checksum', format => {
    const graph = singleMetadataGraph({
      funding: { url: 'https://example.test/fund' },
      license: 'MIT',
    }, berryIntegrity, 'yarn-berry-v8')
    const projected = stringifyProjected(format, graph)
    expect(projected.losses).toEqual(expect.arrayContaining([
      expect.objectContaining({ class: 'structural-expected', feature: 'metadata:funding' }),
      expect.objectContaining({ class: 'structural-expected', feature: 'metadata:license' }),
    ]))
    expect(projected.losses.some(loss => loss.feature === 'metadata:peer-declarations')).toBe(false)
    expect(() => stringify(format, graph)).not.toThrow()
  })

  it.each(['npm-2', 'npm-3'] as const)('%s rejects virtual peer identity flattening', format => {
    const error = caught(format, peerContextGraph())
    expect(error.code).toBe('IRREDUCIBLE_LOSS')
    expect(error.losses?.some(loss => loss.feature === 'peer-context')).toBe(true)
  })

  it('classifies a missing Berry checksum as enrichable and exposes deterministic losses', () => {
    const error = caught('yarn-berry-v9', metadataGraph())
    expect(error.code).toBe('ENRICH_REQUIRED')
    expect(error.message).toMatch(/^berry-checksum projection loss/)
    expect(error.losses).toBeDefined()
    expect(error.losses?.some(loss => loss.class === 'berry-checksum')).toBe(true)
    expect(Object.isFrozen(error.losses)).toBe(true)
  })

  it('uses ENRICH_REQUIRED when Berry checksum is the only loss', () => {
    const graph = metadataGraph().mutate(mutator => {
      mutator.setTarball({ name: 'dep', version: '1.0.0' }, {
        integrity: { hashes: [...sriIntegrity.hashes] },
        resolution: { type: 'tarball', url: 'https://registry.example/dep/-/dep-1.0.0.tgz' },
      })
    }).graph
    const error = caught('yarn-berry-v9', graph)
    expect(error.code).toBe('ENRICH_REQUIRED')
    expect(error.losses?.map(loss => loss.class)).toEqual(['berry-checksum'])
  })

  it('normalizes a completion-created Berry edge independently of checksum repair', async () => {
    const { completed } = await completedBerryIntegrityGraph()
    const diagnostics: Diagnostic[] = []
    stringify(completed.graph, 'yarn-berry-v8', {
      strict: false,
      onDiagnostic: diagnostic => diagnostics.push(diagnostic),
    })
    expect(diagnostics.some(diagnostic =>
      diagnostic.code === 'COMPLETENESS_OUTPUT_GRAPH_MISMATCH')).toBe(false)
    expect(diagnostics).toContainEqual(expect.objectContaining({
      code: 'PROJECTION_LOSS',
      data: expect.objectContaining({ class: 'berry-checksum' }),
    }))
  })

  it('projects a refurbished Berry checksum without discarding retained tarball authority', async () => {
    const { bytes, completed, registryDigest } = await yafMultiOriginIntegrityGraph()
    expect(completed.graph.tarballOf('vuln@2.0.0')?.integrity?.hashes)
      .toEqual([expect.objectContaining({ origin: 'sri' })])

    const source: NpmTarballSource = {
      async tarball(name, version) {
        return name === 'vuln' && version === '2.0.0' ? bytes : undefined
      },
    }
    const repaired = await refurbish(
      completed.graph,
      'yarn-berry-v8',
      { npmTarballs: source },
    )
    expect(repaired.graph.tarballOf('vuln@2.0.0')?.integrity?.hashes.map(hash => hash.origin))
      .toEqual(['sri', 'berry-zip'])

    const diagnostics: Diagnostic[] = []
    expect(() => stringify(repaired.graph, 'yarn-berry-v8', {
      onDiagnostic: diagnostic => diagnostics.push(diagnostic),
    })).not.toThrow()
    expect(repaired.graph.tarballOf('vuln@2.0.0')?.integrity?.hashes.map(hash => hash.origin))
      .toEqual(['sri', 'berry-zip'])
    const npmRoundTrip = parse(
      stringify(repaired.graph, 'npm-3', { strict: false }),
      'npm-3',
    )
    expect(npmRoundTrip.tarballOf('vuln@2.0.0')?.integrity?.hashes)
      .toContainEqual(expect.objectContaining({
        algorithm: 'sha512',
        digest: registryDigest,
        origin: 'sri',
      }))
    expect(diagnostics).toContainEqual(expect.objectContaining({
      code: 'PROJECTION_LOSS',
      subject: 'vuln@2.0.0',
      data: expect.objectContaining({
        class: 'structural-expected',
        feature: 'integrity:tarball-sri',
        target: 'yarn-berry-v8',
      }),
    }))
    expect(diagnostics).toContainEqual(expect.objectContaining({
      code: 'PROJECTION_LOSS',
      subject: 'vuln@2.0.0',
      data: expect.objectContaining({
        class: 'structural-expected',
        feature: 'integrity:url-fragment',
        target: 'yarn-berry-v8',
      }),
    }))
    expect(diagnostics.some(diagnostic =>
      diagnostic.code === 'COMPLETENESS_OUTPUT_GRAPH_MISMATCH')).toBe(false)
  })

  it.each(['yarn-berry-v6', 'yarn-berry-v8'] as const)(
    '%s accepts a producer-authored conditioned builtin-patch lock byte for byte', format => {
      const text = berryConditionalFixture(format)
      expect(stringify(format, parse(format, text))).toBe(text)
    })

  it.each(['yarn-berry-v6', 'yarn-berry-v8'] as const)(
    '%s keeps the unpatched archive sibling checksum beside the patched entry', format => {
      const text = berryConditionalFixture(format)
      const sibling = parse(format, text).tarballOf('fsevents@2.3.3')
      const digest = emitBerryChecksum(sibling?.integrity ?? { hashes: [] })
      expect(digest).toBeDefined()
      expect(stringify(format, parse(format, text))).toContain(digest!)
    })

  it.each(['yarn-berry-v6', 'yarn-berry-v8'] as const)(
    '%s still refuses the unpatched archive sibling once its checksum is dropped', format => {
      const stripped = editBerryEntry(
        berryConditionalFixture(format),
        isArchiveSiblingEntry,
        withoutChecksumLine,
      )
      const error = caught(format, parse(format, stripped))
      expect(error.code).toBe('ENRICH_REQUIRED')
      expect(error.losses).toContainEqual(expect.objectContaining({
        class: 'berry-checksum',
        feature: 'integrity:berry-checksum',
        subject: 'fsevents@2.3.3',
      }))
    })

  it.each([
    ['yarn-berry-v6', `  checksum: ${'ab'.repeat(64)}`],
    ['yarn-berry-v8', `  checksum: 10c0/${'ab'.repeat(64)}`],
  ] as const)('%s round-trips a checksum a patched entry does carry', (format, checksum) => {
    const text = editBerryEntry(
      berryConditionalFixture(format),
      isPatchedFseventsEntry,
      lines => lines.flatMap(line =>
        line.startsWith('  conditions:') ? [checksum, line] : [line]),
    )
    const graph = parse(format, text)
    const patched = [...graph.nodes()].find(node => node.patch !== undefined)!
    expect(emitBerryChecksum(graph.tarballOf(patched.id)?.integrity ?? { hashes: [] }))
      .toBe('ab'.repeat(64))
    expect(stringify(format, graph)).toBe(text)
  })

  it.each([
    ['yarn-berry-v6', '  checksum: deadbeef'],
    ['yarn-berry-v8', '  checksum: 10c0/deadbeef'],
  ] as const)('%s refuses a patched entry whose checksum is present but unparseable',
    (format, checksum) => {
      const text = editBerryEntry(
        berryConditionalFixture(format),
        isPatchedFseventsEntry,
        lines => lines.flatMap(line =>
          line.startsWith('  conditions:') ? [checksum, line] : [line]),
      )
      const error = caught(format, parse(format, text))
      expect(error.losses?.some(loss => loss.class === 'berry-checksum')).toBe(true)
    })

  it.each(['yarn-berry-v6', 'yarn-berry-v8'] as const)(
    '%s still refuses an unconditioned archive-backed entry with no checksum', format => {
      const stripped = editBerryEntry(
        berryConditionalFixture(format),
        isUnconditionedEntry,
        withoutChecksumLine,
      )
      const error = caught(format, parse(format, stripped))
      expect(error.code).toBe('ENRICH_REQUIRED')
      expect(error.losses).toContainEqual(expect.objectContaining({
        class: 'berry-checksum',
        feature: 'integrity:berry-checksum',
        subject: 'graceful-fs@4.2.11',
      }))
    })

  it('accepts a conditioned entry only an optional path reaches', () => {
    const text = conditionedLock('optional')
    expect(stringify('yarn-berry-v8', parse('yarn-berry-v8', text))).toBe(text)
  })

  it('still refuses a conditioned entry a required path reaches', () => {
    const error = caught('yarn-berry-v8', parse('yarn-berry-v8', conditionedLock('required')))
    expect(error.code).toBe('ENRICH_REQUIRED')
    expect(error.losses).toContainEqual(expect.objectContaining({
      class: 'berry-checksum',
      feature: 'integrity:berry-checksum',
      subject: 'cond@1.0.0',
    }))
  })

  it.each(['0.0.0-use.local', '1.2.3'])(
    'accepts a checksum-free link: directory carrying version %s', version => {
      const text = linkedLock(version)
      expect(stringify('yarn-berry-v8', parse('yarn-berry-v8', text))).toBe(text)
    })

  it('preserves a source-authored bare checksum under prefix-era metadata', () => {
    const text = bareChecksumLock()
    const graph = parse('yarn-berry-v8', text)
    expect(stringify('yarn-berry-v8', graph)).toBe(text)
    expect(yarnBerryV9.stringify(graph)).toContain(`  checksum: 10c0/${'ab'.repeat(64)}\n`)
  })

  it('prefixes a checksum minted without Berry source attribution', () => {
    const output = yarnBerryV9.stringify(metadataGraph(berryIntegrity))
    expect(output).toContain(`  checksum: 10c0/${'cd'.repeat(64)}\n`)
  })

  it('still refuses a conditioned entry holding a digest Berry cannot carry', () => {
    // The preflight is asserted directly: the emitter independently reports the
    // same node via RECIPE_INTEGRITY_INCOMPLETE, so a whole-stringify assertion
    // could not tell the two mechanisms apart.
    const parsed = parse('yarn-berry-v8', conditionedLock('optional'))
    expect(projectionPreflightLosses(parsed, { format: 'yarn-berry-v8' })
      .some(loss => loss.class === 'berry-checksum')).toBe(false)

    const graph = parsed.mutate(mutator => {
      mutator.setTarball({ name: 'cond', version: '1.0.0' }, {
        ...parsed.tarballOf('cond@1.0.0'),
        integrity: { hashes: [...sriIntegrity.hashes] },
      })
    }).graph
    expect(projectionPreflightLosses(graph, { format: 'yarn-berry-v8' }))
      .toContainEqual(expect.objectContaining({
        class: 'berry-checksum',
        feature: 'integrity:berry-checksum',
        subject: 'cond@1.0.0',
      }))
    const error = caught('yarn-berry-v8', graph)
    expect(error.code).toBe('ENRICH_REQUIRED')
  })

  it('strict:false preserves legacy bytes and reports accepted loss', () => {
    const graph = metadataGraph()
    const diagnostics: string[] = []
    const expected = yarnBerryV9.stringify(graph)
    const output = stringify('yarn-berry-v9', graph, {
      strict: false,
      onDiagnostic: diagnostic => diagnostics.push(diagnostic.code),
    })
    expect(output).toBe(expected)
    expect(diagnostics).toContain('PROJECTION_LOSS')
  })

  it('lockgraph remains lossless for a source-less hand-built graph', () => {
    expect(() => stringify('lockgraph', metadataGraph())).not.toThrow()
  })
})
