import { describe, expect, it } from 'vitest'
import { convert } from '../../main/ts/index.ts'
import { projectYarnBerryDerivedDependencies } from '../../main/ts/enrich/yarn-berry-derived-dependencies.ts'
import { addEdge, addPackage, graphOf } from './_modify-test-utils.ts'

const npmTarget = { format: 'npm-3' } as const
const berryTarget = { format: 'yarn-berry-v9', managerVersion: '4.14.1' } as const

function seededOwner(name = 'nan', version = '2.22.2') {
  return graphOf(builder => {
    const root = addPackage(builder, { name: 'root', version: '1.0.0', workspacePath: '' })
    const owner = addPackage(builder, { name, version })
    const nodeGyp = addPackage(builder, { name: 'node-gyp', version: '11.5.0' })
    addEdge(builder, root, owner, 'dep', `npm:${version}`)
    addEdge(builder, owner, nodeGyp, 'dep', 'npm:latest')
  })
}

describe('Yarn Berry source-derived dependency projection', () => {
  it('drops an exact proved node-gyp injection only for a non-Berry target', () => {
    const graph = seededOwner()
    const projected = projectYarnBerryDerivedDependencies(
      graph,
      'yarn-berry-v8',
      npmTarget,
    )

    expect(projected.graph).not.toBe(graph)
    expect(projected.graph.out('nan@2.22.2')).toEqual([])
    expect(projected.graph.roots()).toContain('node-gyp@11.5.0')
    expect(projected.unwired).toEqual([{
      src: 'nan@2.22.2',
      dst: 'node-gyp@11.5.0',
      kind: 'dep',
    }])

    const reapplied = projectYarnBerryDerivedDependencies(
      projected.graph,
      'yarn-berry-v8',
      npmTarget,
    )
    expect(reapplied.graph).toBe(projected.graph)
    expect(reapplied.unwired).toEqual([])
  })

  it('retains the edge for Berry targets and non-Berry sources', () => {
    const graph = seededOwner()
    expect(projectYarnBerryDerivedDependencies(
      graph,
      'yarn-berry-v8',
      berryTarget,
    ).graph).toBe(graph)
    expect(projectYarnBerryDerivedDependencies(
      graph,
      'npm-3',
      npmTarget,
    ).graph).toBe(graph)
    expect(projectYarnBerryDerivedDependencies(
      graph,
      'yarn-berry-v6',
      npmTarget,
    ).graph).toBe(graph)
  })

  it('fails closed for an unprofiled package with the same edge spelling', () => {
    const graph = seededOwner('user-native-addon', '1.0.0')
    const projected = projectYarnBerryDerivedDependencies(
      graph,
      'yarn-berry-v8',
      npmTarget,
    )

    expect(projected.graph).toBe(graph)
    expect(projected.unwired).toEqual([])
    expect(graph.out('user-native-addon@1.0.0')).toHaveLength(1)
  })

  it('drops the proved edge from both fsevents base and builtin-patch siblings', () => {
    const graph = graphOf(builder => {
      const nodeGyp = addPackage(builder, { name: 'node-gyp', version: '11.5.0' })
      const base = addPackage(builder, { name: 'fsevents', version: '2.3.3' })
      const patch = addPackage(builder, {
        name: 'fsevents',
        version: '2.3.3',
        patch: `unresolved-${'0'.repeat(64)}`,
      })
      addEdge(builder, base, nodeGyp, 'dep', 'npm:latest')
      addEdge(builder, patch, nodeGyp, 'dep', 'npm:latest')
    })
    const projected = projectYarnBerryDerivedDependencies(
      graph,
      'yarn-berry-v9',
      npmTarget,
    )

    expect(projected.unwired).toHaveLength(2)
    expect(projected.graph.out('fsevents@2.3.3')).toEqual([])
    expect(projected.graph.out(
      `fsevents@2.3.3+patch=unresolved-${'0'.repeat(64)}`,
    )).toEqual([])
  })

  it('removes the injected descriptor from an end-to-end Berry → npm conversion', async () => {
    const source = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    nan: "npm:2.22.2"
  languageName: unknown
  linkType: soft

"nan@npm:2.22.2":
  version: 2.22.2
  resolution: "nan@npm:2.22.2"
  dependencies:
    node-gyp: "npm:latest"
  checksum: 10/aaaa
  languageName: node
  linkType: hard

"node-gyp@npm:latest":
  version: 11.5.0
  resolution: "node-gyp@npm:11.5.0"
  checksum: 10/bbbb
  languageName: node
  linkType: hard
`
    const output = JSON.parse(await convert(source, {
      from: 'yarn-berry-v8',
      to: 'npm-3',
      strict: false,
    })) as {
      packages: Record<string, { dependencies?: Record<string, string> }>
    }

    expect(output.packages['node_modules/nan']).toBeDefined()
    expect(output.packages['node_modules/nan']?.dependencies ?? {})
      .not.toHaveProperty('node-gyp')
  })
})
