import { describe, expect, it } from 'vitest'
import { parse, stringify } from '../../main/ts/index.ts'

// Regression for Bug #88 — a dependency whose descriptor IS a `patch:` locator
// (`patch:<inner>#<patchPath>`, "form b") must link to the PATCH node (the
// `+patch=unresolved-…` sentinel node), not be dropped. Yarn binds an extra
// `::version=…&hash=…[&locator=…]` block onto the patch ENTRY key that the
// consumer's descriptor omits, so the bare descriptor never matched `specIndex`
// → the edge was silently dropped and the patch node left orphaned (0 incoming).
//
// Form a — a plain `npm:` consumer range against an entry whose RESOLUTION
// merely carries a `patch:` locator (entry key stays `<name>@npm:<ver>`) —
// already linked and must keep linking; covered by the control case below.

const FORM_B = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    lodash: "patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch"
  languageName: unknown
  linkType: soft

"lodash@npm:4.17.15":
  version: 4.17.15
  resolution: "lodash@npm:4.17.15"
  checksum: 10c0/aaaa
  languageName: node
  linkType: hard

"lodash@patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch::version=4.17.15&hash=abc123":
  version: 4.17.15
  resolution: "lodash@patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch::version=4.17.15&hash=abc123"
  checksum: 10c0/bbbb
  languageName: node
  linkType: hard
`

// Form b, REVERSED entry order — the patch ENTRY is textually BEFORE the plain
// `npm:` base entry (and before the consumer block resolves them). Source-order
// must not affect resolution: parse builds the patchDescriptorIndex in a first
// pass over ALL entries, so the consumer edge binds regardless of which entry
// appears first. Regression guard for #88's cold-read (idempotence under
// reordered input).
const FORM_B_REVERSED = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"lodash@patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch::version=4.17.15&hash=abc123":
  version: 4.17.15
  resolution: "lodash@patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch::version=4.17.15&hash=abc123"
  checksum: 10c0/bbbb
  languageName: node
  linkType: hard

"lodash@npm:4.17.15":
  version: 4.17.15
  resolution: "lodash@npm:4.17.15"
  checksum: 10c0/aaaa
  languageName: node
  linkType: hard

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    lodash: "patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch"
  languageName: unknown
  linkType: soft
`

// Form a — the real-world shape yarn emits when the consumer declares a plain
// `npm:` range and yarn records the patch on the entry's RESOLUTION (the entry
// key remains `lodash@npm:4.17.21`). This already worked pre-#88; it is the
// control proving the fix does not regress npm:-range consumers.
const FORM_A = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 9
  cacheKey: 10c0

"case-patch-yarn@workspace:.":
  version: 0.0.0-use.local
  resolution: "case-patch-yarn@workspace:."
  dependencies:
    lodash: "npm:4.17.21"
  languageName: unknown
  linkType: soft

"lodash@npm:4.17.21":
  version: 4.17.21
  resolution: "lodash@patch:lodash@npm%3A4.17.21#./.yarn/patches/lodash-npm-4.17.21-6382451519.patch::version=4.17.21&hash=858da5&locator=case-patch-yarn%40workspace%3A."
  checksum: 10c0/d8cbea072bb08655bb4c989da418994b073a608dffa608b09ac04b43a791b12aeae7cd7ad919aa4c925f33b48490b5cfe6c1f71d827956071dae2e7bb3a6b74c
  languageName: node
  linkType: hard
`

const SUM = (nibble: string): string => `10c0/${nibble.repeat(128)}`

// Two consumers patch the SAME package with the SAME patch file but from
// different workspaces → two distinct patch entries that strip to one
// descriptor, disambiguated only by the `&locator=` qualifier. Each consumer's
// bare descriptor must resolve to ITS OWN patch node.
const MULTI = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"a@workspace:packages/a":
  version: 0.0.0-use.local
  resolution: "a@workspace:packages/a"
  dependencies:
    lodash: "patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch"
  languageName: unknown
  linkType: soft

"b@workspace:packages/b":
  version: 0.0.0-use.local
  resolution: "b@workspace:packages/b"
  dependencies:
    lodash: "patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch"
  languageName: unknown
  linkType: soft

"lodash@npm:4.17.15":
  version: 4.17.15
  resolution: "lodash@npm:4.17.15"
  checksum: ${SUM('a')}
  languageName: node
  linkType: hard

"lodash@patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch::version=4.17.15&hash=abc123&locator=a%40workspace%3Apackages%2Fa":
  version: 4.17.15
  resolution: "lodash@patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch::version=4.17.15&hash=abc123&locator=a%40workspace%3Apackages%2Fa"
  checksum: ${SUM('b')}
  languageName: node
  linkType: hard

"lodash@patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch::version=4.17.15&hash=abc123&locator=b%40workspace%3Apackages%2Fb":
  version: 4.17.15
  resolution: "lodash@patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch::version=4.17.15&hash=abc123&locator=b%40workspace%3Apackages%2Fb"
  checksum: ${SUM('c')}
  languageName: node
  linkType: hard
`

describe('yarn-berry patch: descriptor edge resolution (Bug #88)', () => {
  it('form b: a `patch:` consumer descriptor links to the PATCH node', () => {
    const g = parse('yarn-berry-v8', FORM_B)
    const nodes = Array.from(g.nodes())
    expect(nodes.length).toBe(3)

    const root = nodes.find(n => n.name === 'root')!
    const out = g.out(root.id)
    expect(out.length).toBe(1)

    const target = g.getNode(out[0]!.dst)!
    // Resolves to the sentinel patch node, NOT the plain npm: node.
    expect(target.patch).toBeDefined()
    expect(target.patch!.startsWith('unresolved-')).toBe(true)
    expect(g.tarballOf(target.id)?.nativeResolution).toBe(
      'lodash@patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch::version=4.17.15&hash=abc123')

    // The plain npm: node exists but has ZERO incoming edges (it is the patch's
    // base, not the consumer's target).
    const npmNode = nodes.find(n => n.name === 'lodash' && n.patch === undefined)!
    expect(g.in(npmNode.id).length).toBe(0)
    // The patch node now has the consumer edge it was missing.
    expect(g.in(target.id).length).toBe(1)

    // The orphaning diagnostic is gone.
    const unresolved = g.diagnostics().filter(d => d.code === 'YARN_BERRY_UNRESOLVED_DEP')
    expect(unresolved.length).toBe(0)
  })

  it('form b round-trips: stringify → reparse preserves the 3 nodes + the edge', () => {
    const g = parse('yarn-berry-v8', FORM_B)
    const out = stringify('yarn-berry-v8', g, { strict: false })
    // The patch node round-trips its verbatim `patch:` resolution (its emitted
    // entry key is a compound key whose primary spec is the full locator); both
    // the plain npm: base and the bare consumer descriptor ride along as
    // secondary specs in that compound key.
    expect(out).toContain(
      'resolution: "lodash@patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch::version=4.17.15&hash=abc123"')
    expect(out).toContain('resolution: "lodash@npm:4.17.15"')

    // Reparse is semantically clean: same 3 nodes, the consumer→patch edge
    // survives, and no UNRESOLVED_DEP / IRREDUCIBLE_LOSS is introduced.
    const g2 = parse('yarn-berry-v8', out)
    const nodes2 = Array.from(g2.nodes())
    expect(nodes2.length).toBe(3)

    const root2 = nodes2.find(n => n.name === 'root')!
    const out2 = g2.out(root2.id)
    expect(out2.length).toBe(1)
    const target2 = g2.getNode(out2[0]!.dst)!
    expect(target2.patch!.startsWith('unresolved-')).toBe(true)
    // The plain npm: node stays distinct (its base spec did not collapse the
    // patch node away) and still carries no consumer edge.
    const npm2 = nodes2.find(n => n.name === 'lodash' && n.patch === undefined)!
    expect(g2.in(npm2.id).length).toBe(0)

    expect(g2.diagnostics().filter(d => d.code === 'YARN_BERRY_UNRESOLVED_DEP').length).toBe(0)
  })

  it('form b REVERSED order: patch entry before npm entry — stable, idempotent, edge intact', () => {
    const g = parse('yarn-berry-v8', FORM_B_REVERSED)
    const nodes = Array.from(g.nodes())
    expect(nodes.length).toBe(3)

    // The root→patch-node edge binds despite the patch entry preceding its base.
    const root = nodes.find(n => n.name === 'root')!
    const out = g.out(root.id)
    expect(out.length).toBe(1)
    const target = g.getNode(out[0]!.dst)!
    expect(target.patch!.startsWith('unresolved-')).toBe(true)
    expect(g.tarballOf(target.id)?.nativeResolution).toBe(
      'lodash@patch:lodash@npm%3A4.17.15#~/.yarn/patches/lodash.patch::version=4.17.15&hash=abc123')
    // The plain npm: base stays a distinct node with zero incoming edges.
    const npmNode = nodes.find(n => n.name === 'lodash' && n.patch === undefined)!
    expect(g.in(npmNode.id).length).toBe(0)
    expect(g.in(target.id).length).toBe(1)
    expect(g.diagnostics().filter(d => d.code === 'YARN_BERRY_UNRESOLVED_DEP').length).toBe(0)

    // Stringify TWICE → byte-identical (source-order independence + idempotence).
    const once = stringify('yarn-berry-v8', g, { strict: false })
    const twice = stringify('yarn-berry-v8', parse('yarn-berry-v8', once), { strict: false })
    expect(twice).toBe(once)

    // The reparsed graph keeps the root→patch edge.
    const g2 = parse('yarn-berry-v8', once)
    const root2 = Array.from(g2.nodes()).find(n => n.name === 'root')!
    const out2 = g2.out(root2.id)
    expect(out2.length).toBe(1)
    expect(g2.getNode(out2[0]!.dst)!.patch!.startsWith('unresolved-')).toBe(true)
  })

  it('control (form a): a plain npm: consumer still links to its patch node', () => {
    const g = parse('yarn-berry-v9', FORM_A)
    const nodes = Array.from(g.nodes())
    // Form a has no separate plain-npm node: the only `lodash` entry IS the
    // patch node (patch lives on its resolution, key stays npm:).
    expect(nodes.length).toBe(2)

    const root = nodes.find(n => n.name === 'case-patch-yarn')!
    const out = g.out(root.id)
    expect(out.length).toBe(1)
    expect(out[0]!.attrs?.range).toBe('4.17.21')

    const target = g.getNode(out[0]!.dst)!
    expect(target.patch!.startsWith('unresolved-')).toBe(true)

    expect(g.diagnostics().filter(d => d.code === 'YARN_BERRY_UNRESOLVED_DEP').length).toBe(0)
  })

  it('form b builtin: a `~builtin<…>` patch descriptor links to the patch node', () => {
    const BUILTIN = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    typescript: "patch:typescript@npm%3A5.4.5#~builtin<compat/typescript>"
  languageName: unknown
  linkType: soft

"typescript@npm:5.4.5":
  version: 5.4.5
  resolution: "typescript@npm:5.4.5"
  checksum: ${SUM('a')}
  languageName: node
  linkType: hard

"typescript@patch:typescript@npm%3A5.4.5#~builtin<compat/typescript>::version=5.4.5&hash=14eedb":
  version: 5.4.5
  resolution: "typescript@patch:typescript@npm%3A5.4.5#~builtin<compat/typescript>::version=5.4.5&hash=14eedb"
  checksum: ${SUM('b')}
  languageName: node
  linkType: hard
`
    const g = parse('yarn-berry-v8', BUILTIN)
    const root = Array.from(g.nodes()).find(n => n.name === 'root')!
    const out = g.out(root.id)
    expect(out.length).toBe(1)
    expect(g.getNode(out[0]!.dst)!.patch!.startsWith('unresolved-')).toBe(true)
    expect(g.diagnostics().filter(d => d.code === 'YARN_BERRY_UNRESOLVED_DEP').length).toBe(0)
  })

  it('form b nested: a patch-of-patch descriptor links to the OUTER patch node', () => {
    // Yarn percent-encodes the INNER locator's `#`/`::` (`%23`/`%3A%3A`), so the
    // outer `::`-param strip still lands on the outer patch's params.
    const NESTED = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    lodash: "patch:lodash@patch%3Alodash@npm%253A4.17.15%23~/.yarn/patches/inner.patch%3A%3Aversion=4.17.15&hash=inner1#~/.yarn/patches/outer.patch"
  languageName: unknown
  linkType: soft

"lodash@npm:4.17.15":
  version: 4.17.15
  resolution: "lodash@npm:4.17.15"
  checksum: ${SUM('a')}
  languageName: node
  linkType: hard

"lodash@patch:lodash@patch%3Alodash@npm%253A4.17.15%23~/.yarn/patches/inner.patch%3A%3Aversion=4.17.15&hash=inner1#~/.yarn/patches/outer.patch::version=4.17.15&hash=outer1":
  version: 4.17.15
  resolution: "lodash@patch:lodash@patch%3Alodash@npm%253A4.17.15%23~/.yarn/patches/inner.patch%3A%3Aversion=4.17.15&hash=inner1#~/.yarn/patches/outer.patch::version=4.17.15&hash=outer1"
  checksum: ${SUM('b')}
  languageName: node
  linkType: hard
`
    const g = parse('yarn-berry-v8', NESTED)
    const nodes = Array.from(g.nodes())
    expect(nodes.length).toBe(3)
    const root = nodes.find(n => n.name === 'root')!
    const out = g.out(root.id)
    expect(out.length).toBe(1)
    const target = g.getNode(out[0]!.dst)!
    expect(target.patch!.startsWith('unresolved-')).toBe(true)
    // Links to the patch node, not the plain npm: base.
    expect(g.tarballOf(out[0]!.dst)?.nativeResolution).toContain('#~/.yarn/patches/outer.patch')
    expect(g.diagnostics().filter(d => d.code === 'YARN_BERRY_UNRESOLVED_DEP').length).toBe(0)
  })

  it('multi-consumer: each bare descriptor resolves to its own locator-tagged patch node', () => {
    const g = parse('yarn-berry-v8', MULTI)
    const nodes = Array.from(g.nodes())
    // root-a, root-b, plain npm lodash, + 2 distinct patch nodes.
    expect(nodes.length).toBe(5)

    const a = nodes.find(n => n.name === 'a')!
    const b = nodes.find(n => n.name === 'b')!
    const aTarget = g.getNode(g.out(a.id)[0]!.dst)!
    const bTarget = g.getNode(g.out(b.id)[0]!.dst)!

    // Distinct patch nodes, each carrying its consumer's `&locator=`.
    expect(aTarget.id).not.toBe(bTarget.id)
    expect(g.tarballOf(aTarget.id)?.nativeResolution).toContain('locator=a%40workspace%3Apackages%2Fa')
    expect(g.tarballOf(bTarget.id)?.nativeResolution).toContain('locator=b%40workspace%3Apackages%2Fb')
    expect(aTarget.patch!.startsWith('unresolved-')).toBe(true)
    expect(bTarget.patch!.startsWith('unresolved-')).toBe(true)

    expect(g.diagnostics().filter(d => d.code === 'YARN_BERRY_UNRESOLVED_DEP').length).toBe(0)
  })
})
