import { describe, expect, it } from 'vitest'
import { check, parse, stringify } from '../../main/ts/formats/yarn-classic.ts'
import { detect } from '../../main/ts/index.ts'
import { removeDependency } from '../../main/ts/modify/remove-dependency.ts'

// yarn-classic parse edge cases: bare/unquoted dependency values, UTF-8 BOM
// detection, header-only (empty) lockfiles, legacy unknown entry fields.

const H =
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n' +
  '# yarn lockfile v1\n\n\n'
const BOM = String.fromCharCode(0xfeff) // U+FEFF, no raw BOM glyph in source

describe('yarn-classic — parse edge cases', () => {
  // Bare (unquoted) dependency value: dist-tag, v-prefixed version. yarn 1
  // emits these forms unquoted.
  it('parses bare dist-tag + v-prefixed dependency values', () => {
    const lock =
      H +
      'foo@^1.0.0:\n' +
      '  version "1.0.0"\n' +
      '  resolved "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz#aaa"\n' +
      '  dependencies:\n' +
      '    bar latest\n' +
      '    baz v0.5.0\n' +
      '\n' +
      'bar@latest:\n' +
      '  version "2.0.0"\n' +
      '  resolved "https://registry.yarnpkg.com/bar/-/bar-2.0.0.tgz#bbb"\n' +
      '\n' +
      'baz@v0.5.0:\n' +
      '  version "0.5.0"\n' +
      '  resolved "https://registry.yarnpkg.com/baz/-/baz-0.5.0.tgz#ccc"\n'
    expect(() => parse(lock)).not.toThrow()
    const g = parse(lock)
    const foo = g.getNode('foo@1.0.0')
    expect(foo).toBeDefined()
    const deps = g.out(foo!.id).map(e => e.dst).sort()
    expect(deps).toContain('bar@2.0.0')
    expect(deps).toContain('baz@0.5.0')
  })

  // yarn-1 legacy `uid` field on link:/file: entries. The parser threw
  // `unsupported entry field`; now it is TOLERATED + round-tripped verbatim
  // (forward-compat for any unmodelled scalar entry field).
  it('tolerates + round-trips the legacy `uid` field (link: entry)', () => {
    const lock =
      H +
      '"my-internal-rules@link:./scripts/eslint-rules":\n' +
      '  version "0.0.0"\n' +
      '  uid ""\n'
    expect(() => parse(lock)).not.toThrow()
    const g = parse(lock)
    expect(g.getNode('my-internal-rules@0.0.0')).toBeDefined()
    // uid round-trips verbatim
    const out = stringify(g)
    expect(out).toContain('  uid ""')
    // re-parse is stable (idempotent) and still carries uid
    expect(stringify(parse(out))).toBe(out)
  })

  // A leading UTF-8 BOM must not defeat detect (was asymmetric: berry detected,
  // classic did not).
  it('detects + parses a v1 lockfile with a leading UTF-8 BOM', () => {
    const lock = BOM + H + 'foo@^1.0.0:\n  version "1.0.0"\n  resolved "https://r/foo#a"\n'
    expect(check(lock)).toBe(true)
    expect(detect(lock)).toBe('yarn-classic')
    expect(() => parse(lock)).not.toThrow()
    // ADR-0032 — `https://r/foo` is a NON-registry-host tarball, so `foo`
    // carries a `+src=` discriminator; address it by name.
    expect(parse(lock).byName('foo').length).toBe(1)
  })

  // Header-only (fresh-init, empty) v1 lockfile: detect + empty graph (was
  // asymmetric: berry → empty graph, classic → no detect).
  it('detects + parses a header-only v1 lockfile as an empty graph', () => {
    const headerOnly = '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n'
    expect(check(headerOnly)).toBe(true)
    expect(detect(headerOnly)).toBe('yarn-classic')
    expect(Array.from(parse(headerOnly).nodes())).toEqual([])
  })
})

// C-KEYDROP — a multi-descriptor entry key whose merged descriptors do NOT all
// have an in-lock consumer must NOT lose the consumer-less ("orphan") descriptors
// on format(parse(x)). This reproduces the facebook/react@557e28f data loss in
// miniature: react's `@babel/core` entry key carries five `^7.x` ranges, two of
// which (`^7.11.1`, `^7.24.4`) are declared only by a workspace whose
// package.json is absent from the parsed lock — so they have no incoming edge,
// orphan, and were DROPPED from the re-emitted key (a consumer of the dropped
// range then no longer finds its locked entry → re-resolution). The fix unions
// the live-edge-reconstructed descriptors with the verbatim parse-time
// entry-key sidecar, so every on-disk descriptor round-trips.
describe('yarn-classic — entry-key orphan descriptors round-trip (C-KEYDROP)', () => {
  // The `<descriptors>:` head lines, parsed into per-entry descriptor sets.
  function entryKeyDescriptorSets(lock: string): string[][] {
    const out: string[][] = []
    for (const line of lock.replace(/\r\n/g, '\n').split('\n')) {
      if (line.length === 0 || line[0] === ' ' || line[0] === '\t' || line[0] === '#') continue
      if (!line.endsWith(':')) continue
      const key = line.slice(0, -1)
      const raw: string[] = []
      let start = 0, quoted = false, escaped = false
      for (let i = 0; i < key.length; i++) {
        const c = key[i]
        if (escaped) { escaped = false; continue }
        if (c === '\\') { escaped = true; continue }
        if (c === '"') { quoted = !quoted; continue }
        if (!quoted && c === ',' && key[i + 1] === ' ') { raw.push(key.slice(start, i)); start = i + 2; i++ }
      }
      raw.push(key.slice(start))
      out.push(raw.map(t => {
        if (!t.startsWith('"')) return t
        let v = ''
        for (let i = 1; i < t.length - 1; i++) {
          const c = t[i]
          if (c !== '\\') { v += c; continue }
          v += t[++i]
        }
        return v
      }))
    }
    return out
  }

  it('preserves consumer-less (orphan) descriptors of a 5-range @babel/core key (react@557e28f repro)', () => {
    // A second + third in-lock consumer so `^7.11.6`, `^7.12.3`, `^7.23.9` are
    // all edge-backed and ONLY `^7.11.1` + `^7.24.4` orphan (the react finding).
    const lock =
      H +
      '"@babel/core@^7.11.1", "@babel/core@^7.11.6", "@babel/core@^7.12.3", "@babel/core@^7.23.9", "@babel/core@^7.24.4":\n' +
      '  version "7.24.5"\n' +
      '  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.5.tgz#aaa"\n' +
      '\n' +
      'consumer-a@^1.0.0:\n' +
      '  version "1.0.0"\n' +
      '  resolved "https://registry.yarnpkg.com/consumer-a/-/consumer-a-1.0.0.tgz#bbb"\n' +
      '  dependencies:\n' +
      '    "@babel/core" "^7.11.6"\n' +
      '\n' +
      'consumer-b@^1.0.0:\n' +
      '  version "1.0.0"\n' +
      '  resolved "https://registry.yarnpkg.com/consumer-b/-/consumer-b-1.0.0.tgz#ccc"\n' +
      '  dependencies:\n' +
      '    "@babel/core" "^7.12.3"\n' +
      '\n' +
      'consumer-c@^1.0.0:\n' +
      '  version "1.0.0"\n' +
      '  resolved "https://registry.yarnpkg.com/consumer-c/-/consumer-c-1.0.0.tgz#ddd"\n' +
      '  dependencies:\n' +
      '    "@babel/core" "^7.23.9"\n'

    const g = parse(lock)
    // Two of the five ranges (`^7.11.1`, `^7.24.4`) have no in-lock consumer edge.
    const babelIn = g.in('@babel/core@7.24.5')
      .filter(e => e.kind === 'dep' || e.kind === 'optional')
      .map(e => e.attrs?.range)
      .sort()
    expect(babelIn).toEqual(['^7.11.6', '^7.12.3', '^7.23.9'])

    const out = stringify(g)
    const emittedBabelKey = entryKeyDescriptorSets(out)
      .find(set => set.some(d => d.startsWith('@babel/core@')))
    expect(emittedBabelKey, 'no @babel/core entry key emitted').toBeDefined()
    // The full five-range descriptor SET survives — the two orphans included.
    expect([...emittedBabelKey!].sort()).toEqual([
      '@babel/core@^7.11.1',
      '@babel/core@^7.11.6',
      '@babel/core@^7.12.3',
      '@babel/core@^7.23.9',
      '@babel/core@^7.24.4',
    ])
    // Byte round-trip: the emitted lock re-emits identically (idempotent).
    expect(stringify(parse(out))).toBe(out)
  })

  // The simplest possible repro: a two-descriptor key where ONE range has no
  // in-lock consumer. Pre-fix the orphan `a@^2.0.0` was dropped (live-only emit);
  // post-fix the union with the verbatim sidecar preserves it.
  it('preserves the orphan range of a 2-descriptor key (a@^1, a@^2 — only ^1 consumed)', () => {
    const lock =
      H +
      'a@^1.0.0, a@^2.0.0:\n' +
      '  version "2.5.0"\n' +
      '  resolved "https://registry.yarnpkg.com/a/-/a-2.5.0.tgz#aaa"\n' +
      '\n' +
      'b@^1.0.0:\n' +
      '  version "1.0.0"\n' +
      '  resolved "https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#bbb"\n' +
      '  dependencies:\n' +
      '    a "^1.0.0"\n'

    const g = parse(lock)
    // Only `^1.0.0` has an in-lock consumer edge.
    expect(g.in('a@2.5.0').filter(e => e.kind === 'dep').map(e => e.attrs?.range)).toEqual(['^1.0.0'])

    const out = stringify(g)
    const aKey = entryKeyDescriptorSets(out).find(set => set.some(d => d.startsWith('a@')))
    expect([...aKey!].sort()).toEqual(['a@^1.0.0', 'a@^2.0.0'])
    expect(stringify(parse(out))).toBe(out)
  })
})

// C-KEYDROP (full fix) — the verbatim entry-key descriptor sidecar must survive
// `graph.mutate()`. The sidecar is a per-graph WeakMap, but every modify
// primitive (and optimize/enrich) builds a BRAND-NEW Graph via graph.mutate();
// without the `withSidecarPropagation` wrapper the new graph has no sidecar
// entry, so `entrySpecsOfNode` falls back to live edges only and the orphan key
// descriptors of an UNTOUCHED node drop again — the react@557e28f data loss on
// the audit-fix (parse → modify → stringify) path. These tests fail on the
// pre-wrapper worktree and pass after it.
describe('yarn-classic — orphan descriptors survive graph.mutate (C-KEYDROP audit-fix path)', () => {
  // Parse the emitted entry-key head lines into per-entry descriptor sets
  // (un-quoting each descriptor). Same helper as the read→write block above.
  function entryKeyDescriptorSets(lock: string): string[][] {
    const out: string[][] = []
    for (const line of lock.replace(/\r\n/g, '\n').split('\n')) {
      if (line.length === 0 || line[0] === ' ' || line[0] === '\t' || line[0] === '#') continue
      if (!line.endsWith(':')) continue
      const key = line.slice(0, -1)
      const raw: string[] = []
      let start = 0, quoted = false, escaped = false
      for (let i = 0; i < key.length; i++) {
        const c = key[i]
        if (escaped) { escaped = false; continue }
        if (c === '\\') { escaped = true; continue }
        if (c === '"') { quoted = !quoted; continue }
        if (!quoted && c === ',' && key[i + 1] === ' ') { raw.push(key.slice(start, i)); start = i + 2; i++ }
      }
      raw.push(key.slice(start))
      out.push(raw.map(t => {
        if (!t.startsWith('"')) return t
        let v = ''
        for (let i = 1; i < t.length - 1; i++) {
          const c = t[i]
          if (c !== '\\') { v += c; continue }
          v += t[++i]
        }
        return v
      }))
    }
    return out
  }

  // X = `a@2.5.0` carries an orphan descriptor `a@^2.0.0` (no in-lock consumer);
  // its only live edge is `a@^1.0.0` (from `b`). Y = `b` is the modify target.
  const LOCK =
    H +
    'a@^1.0.0, a@^2.0.0:\n' +
    '  version "2.5.0"\n' +
    '  resolved "https://registry.yarnpkg.com/a/-/a-2.5.0.tgz#aaa"\n' +
    '\n' +
    'app@^0.0.0:\n' +
    '  version "0.0.0"\n' +
    '  resolved "https://registry.yarnpkg.com/app/-/app-0.0.0.tgz#000"\n' +
    '  dependencies:\n' +
    '    a "^1.0.0"\n' +
    '    spare "^1.0.0"\n' +
    '\n' +
    'b@^1.0.0:\n' +
    '  version "1.0.0"\n' +
    '  resolved "https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#bbb"\n' +
    '\n' +
    'spare@^1.0.0:\n' +
    '  version "1.0.0"\n' +
    '  resolved "https://registry.yarnpkg.com/spare/-/spare-1.0.0.tgz#ccc"\n'

  const aKeyOf = (lock: string): string[] | undefined =>
    entryKeyDescriptorSets(lock).find(set => set.some(d => d.startsWith('a@')))

  it('a bare graph.mutate() on an UNRELATED node keeps node a@2.5.0`s orphan a@^2.0.0', () => {
    const g = parse(LOCK)
    // Only `^1.0.0` is edge-backed; `^2.0.0` is a consumer-less orphan.
    expect(g.in('a@2.5.0').filter(e => e.kind === 'dep').map(e => e.attrs?.range)).toEqual(['^1.0.0'])

    // Audit-fix-style: drop an edge from a DIFFERENT node (app → spare), then GC.
    const mutated = g.mutate(m => {
      m.removeEdge('app@0.0.0', 'spare@1.0.0', 'dep')
      m.removeNode('spare@1.0.0')
    }).graph

    // a@2.5.0 was untouched — its full on-disk descriptor set must survive.
    const out = stringify(mutated)
    expect(aKeyOf(out), 'no a@ entry key emitted after mutate').toBeDefined()
    expect([...aKeyOf(out)!].sort()).toEqual(['a@^1.0.0', 'a@^2.0.0'])
    expect(stringify(parse(out))).toBe(out)
  })

  it('audit-fix removeDependency on a DIFFERENT node keeps node a@2.5.0`s orphan a@^2.0.0', async () => {
    const g = parse(LOCK)

    // The real audit-fix primitive: remove app -> spare. This GC-sweeps `spare`
    // and runs entirely through graph.mutate(), the exact path that re-builds
    // the Graph and (pre-fix) loses the sidecar.
    const result = await removeDependency(g, 'app@0.0.0', 'spare')
    expect(result.removed).toContain('spare@1.0.0')
    expect(result.graph.getNode('a@2.5.0')).toBeDefined()

    const out = stringify(result.graph)
    expect(aKeyOf(out), 'no a@ entry key emitted after removeDependency').toBeDefined()
    // The untouched a@2.5.0 node keeps BOTH descriptors — orphan a@^2.0.0 survives.
    expect([...aKeyOf(out)!].sort()).toEqual(['a@^1.0.0', 'a@^2.0.0'])
    expect(stringify(parse(out))).toBe(out)
  })

  // A genuine VERSION bump of the orphan-bearing node ITSELF legitimately resets
  // its key — the old version's orphan ranges do not apply to the new version, so
  // they must NOT carry across the bump. The replacement reconstructs its key from
  // live edges. This is the deliberate identity-change reset (#114 carries ONLY
  // identity-PRESERVING renames — see the replacePeerContext test below), NOT the
  // data loss the wrapper fixes — verify the wrapper does not over-reach into it.
  it('a version-bump of node a ITSELF resets its key (orphan a@^2.0.0 does NOT carry to the new version)', () => {
    const g = parse(LOCK)

    // Mint a NEW NodeId for the orphan-bearing node (a@2.5.0 -> a@3.0.0) and
    // retarget app`s live edge onto it (app is a`s only in-lock consumer). This
    // is the rename shape every modify primitive produces for a self-bump; the
    // old NodeId leaves the graph, so its sidecar entry is pruned.
    const renamed = g.mutate(m => {
      m.removeEdge('app@0.0.0', 'a@2.5.0', 'dep')
      m.addNode({ id: 'a@3.0.0', name: 'a', version: '3.0.0', peerContext: [] })
      m.addEdge('app@0.0.0', 'a@3.0.0', 'dep', { range: '^3.0.0' })
      m.removeNode('a@2.5.0')
    }).graph

    const out = stringify(renamed)
    // The bumped node`s key is reconstructed from its single live edge ONLY —
    // the stale orphan `a@^2.0.0` (and the old `a@^1.0.0`) are gone.
    const newKey = entryKeyDescriptorSets(out).find(set => set.some(d => d.startsWith('a@')))
    expect(newKey, 'no a@ entry key after rename').toBeDefined()
    expect([...newKey!].sort()).toEqual(['a@^3.0.0'])
    expect(out).not.toContain('a@^2.0.0')
    expect(out).not.toContain('a@2.5.0')
    expect(stringify(parse(out))).toBe(out)
  })

  // #114 — an IDENTITY-PRESERVING rename (a peerContext shift that keeps the
  // `name@version` base) must CARRY the verbatim entry-key descriptors — incl. the
  // consumer-less orphan — onto the renamed node. This is the audit-fix shape that
  // virtualizes a peer consumer (replacePeerContext) on a node whose on-disk key
  // held orphans; pre-fix the sidecar was keyed by the old id and pruned by the
  // rename, re-dropping the orphan (the react@557e28f loss returning under a peer
  // re-key). Distinct from the version-bump RESET above: the base key is unchanged.
  // NB: yarn-classic v1 has no `peerDependencies:` entry block (berry-only). The
  // peer edge here is introduced PROGRAMMATICALLY via replacePeerContext — exactly
  // how a modify pass virtualizes a consumer — so `peer@1.0.0` is just a sibling
  // node to re-key onto. `pc`'s on-disk key carries the orphan `pc@^2.0.0`.
  const PEER_LOCK =
    H +
    '"pc@^1.0.0, pc@^2.0.0":\n' +           // orphan `^2.0.0` (no in-lock consumer)
    '  version "1.0.0"\n' +
    '  resolved "https://registry.yarnpkg.com/pc/-/pc-1.0.0.tgz#ppp"\n' +
    '\n' +
    'app@^0.0.0:\n' +
    '  version "0.0.0"\n' +
    '  resolved "https://registry.yarnpkg.com/app/-/app-0.0.0.tgz#000"\n' +
    '  dependencies:\n' +
    '    pc "^1.0.0"\n' +
    '\n' +
    'peer@^1.0.0:\n' +
    '  version "1.0.0"\n' +
    '  resolved "https://registry.yarnpkg.com/peer/-/peer-1.0.0.tgz#eee"\n'

  it('replacePeerContext (identity-preserving) on the orphan-bearing node KEEPS its orphan pc@^2.0.0', () => {
    const g = parse(PEER_LOCK)
    // Only `^1.0.0` is edge-backed; `^2.0.0` is a consumer-less orphan.
    expect(g.getNode('pc@1.0.0')).toBeDefined()
    const pcKeyBefore = entryKeyDescriptorSets(stringify(g)).find(set => set.some(d => d.startsWith('pc@')))
    expect([...pcKeyBefore!].sort()).toEqual(['pc@^1.0.0', 'pc@^2.0.0'])

    // Re-key pc's peerContext onto peer@1.0.0 — base `pc@1.0.0` is UNCHANGED, so
    // this is identity-preserving; the new id is `pc@1.0.0(peer@1.0.0)`.
    const result = g.mutate(m => {
      m.replacePeerContext('pc@1.0.0', ['peer@1.0.0'])
    })
    expect(result.applied).toEqual([
      { kind: 'peer-context-replaced', subject: 'pc@1.0.0(peer@1.0.0)', previous: 'pc@1.0.0' },
    ])
    expect(result.graph.getNode('pc@1.0.0(peer@1.0.0)')).toBeDefined()

    // The verbatim entry-key descriptors followed the rename — the orphan survives.
    const out = stringify(result.graph)
    const pcKeyAfter = entryKeyDescriptorSets(out).find(set => set.some(d => d.startsWith('pc@')))
    expect(pcKeyAfter, 'no pc@ entry key after rename').toBeDefined()
    expect([...pcKeyAfter!].sort()).toEqual(['pc@^1.0.0', 'pc@^2.0.0'])
    expect(out).toContain('pc@^2.0.0')
    expect(stringify(parse(out))).toBe(out)
  })
})
