import { describe, expect, it } from 'vitest'

import { parse } from '../../main/ts/index.ts'

const LOCK = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

prettier-2@npm:prettier@^2:
  version "2.8.8"
  resolved "https://registry.yarnpkg.com/prettier/-/prettier-2.8.8.tgz"

prettier@^3.8.2:
  version "3.8.3"
  resolved "https://registry.yarnpkg.com/prettier/-/prettier-3.8.3.tgz"
`

const MANIFESTS = {
  '': {
    name: 'app',
    version: '1.0.0',
    workspaces: ['packages/member'],
    dependencies: {
      member: 'workspace:*',
    },
    devDependencies: {
      'prettier-2': 'npm:prettier@^2',
      prettier: '^3.8.2',
    },
  },
  'packages/member': {
    name: 'member',
    version: '1.0.0',
    dependencies: {
      'prettier-2': 'npm:prettier@^2',
    },
  },
}

describe('Yarn Classic manifest-derived alias edges — red-first regressions', () => {
  it('retains the declared alias on a synthesized root edge', () => {
    const graph = parse('yarn-classic', LOCK, { manifests: MANIFESTS })
    const edge = graph.out('app@1.0.0', 'dev')
      .find(candidate => candidate.dst === 'prettier@2.8.8')

    expect(edge?.attrs).toEqual({
      range: 'npm:prettier@^2',
      alias: 'prettier-2',
    })
  })

  it('retains the declared alias on a synthesized workspace-member edge', () => {
    const graph = parse('yarn-classic', LOCK, { manifests: MANIFESTS })
    const edge = graph.out('member@1.0.0', 'dep')
      .find(candidate => candidate.dst === 'prettier@2.8.8')

    expect(edge?.attrs).toEqual({
      range: 'npm:prettier@^2',
      alias: 'prettier-2',
    })
  })
})

describe('Yarn Classic manifest-derived alias edges — boundary guards', () => {
  it('does not mark an ordinary same-name declaration as an alias', () => {
    const graph = parse('yarn-classic', LOCK, { manifests: MANIFESTS })
    const edge = graph.out('app@1.0.0', 'dev')
      .find(candidate => candidate.dst === 'prettier@3.8.3')

    expect(edge?.attrs).toEqual({ range: '^3.8.2' })
  })

  it('keeps workspace protocol attribution separate from alias identity', () => {
    const graph = parse('yarn-classic', LOCK, { manifests: MANIFESTS })
    const edge = graph.out('app@1.0.0', 'dep')
      .find(candidate => candidate.dst === 'member@1.0.0')

    expect(edge?.attrs?.alias).toBeUndefined()
    expect(edge?.attrs?.workspace).toBe(true)
    expect(edge?.attrs?.workspaceRange).toEqual({
      specifier: 'workspace:*',
      resolvedVersion: '1.0.0',
    })
  })
})
