import { describe, expect, it } from 'vitest'
import { createHash } from 'node:crypto'
import { detect, parse, stringify } from '../../main/ts/index.ts'
import { LockfileError } from '../../main/ts/api/errors.ts'

// Robustness gaps from the yarn-audit-fix real-world sweep (snapshot.49).
// Minimal repros only — no external fixtures.

const ANSI_SRI = 'sha512-zbB9rCJAt1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg=='

// Valid-length SRI members for the F5 multi-hash tests (sha1 = 20 bytes / 28
// base64 chars; sha512 = 64 bytes / 88). Derived from `seed` so each is a real,
// re-parseable digest of the correct algorithm length.
const sri1 = (seed: string): string => 'sha1-' + createHash('sha1').update(seed).digest('base64')
const sri512 = (seed: string): string => 'sha512-' + createHash('sha512').update(seed).digest('base64')

describe('yarn-classic robustness — git-protocol resolved URLs', () => {
  it('a git+ssh resolved URL parses (modelled as a git resolution), not a whole-file abort', () => {
    const lf =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      'from-git@git+ssh://git@github.com/example/from-git.git:\n' +
      '  version "0.0.0"\n' +
      '  resolved "git+ssh://git@github.com/example/from-git.git#0123456789abcdef0123456789abcdef01234567"\n'
    const g = parse('yarn-classic', lf)
    // ADR-0032 — a git source carries a `+src=` discriminator; address by name.
    const id = g.byName('from-git')[0]!
    expect(g.getNode(id)).toBeDefined()
    expect(id).toContain('+src=')
    expect(g.tarballOf(id)?.nativeResolution).toBe('git+ssh://git@github.com/example/from-git.git#0123456789abcdef0123456789abcdef01234567')
    expect(g.tarballOf(id)?.resolution?.type).toBe('git')
  })

  it('git:// and scp-like git@ forms also parse', () => {
    const lf =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      '"ws@git://github.com/frozeman/WebSocket-Node.git":\n' +
      '  version "1.0.0"\n' +
      '  resolved "git://github.com/frozeman/WebSocket-Node.git#deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"\n'
    const g = parse('yarn-classic', lf)
    // ADR-0032 — a git source carries a `+src=` discriminator; address by name.
    const id = g.byName('ws')[0]!
    expect(g.tarballOf(id)?.nativeResolution).toMatch(/^git:\/\//)
    expect(g.tarballOf(id)?.resolution?.type).toBe('git')
  })

  // F2 (snapshot.50 round-trip sweep): the git `resolved` line must SURVIVE
  // emit. snapshot.50 made git deps parse, but stringify re-emitted the entry
  // WITHOUT its `resolved "git+ssh://…#sha"` line — a lockfile `yarn install
  // --immutable` rejects. `formatResolution` now round-trips any URL shape
  // `parseResolution` accepts (the verbatim Node.resolution path).
  it('a git+ssh resolved line round-trips on emit (F2)', () => {
    const lf =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      'from-git@git+ssh://git@github.com/example/from-git.git:\n' +
      '  version "0.0.0"\n' +
      '  resolved "git+ssh://git@github.com/example/from-git.git#abc123"\n'
    const out = stringify('yarn-classic', parse('yarn-classic', lf))
    expect(out).toContain('resolved "git+ssh://git@github.com/example/from-git.git#abc123"')
  })

  it('a git+ssh resolved line with a 40-hex sha round-trips on emit (F2)', () => {
    const lf =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      'from-git@git+ssh://git@github.com/example/from-git.git:\n' +
      '  version "0.0.0"\n' +
      '  resolved "git+ssh://git@github.com/example/from-git.git#0123456789abcdef0123456789abcdef01234567"\n'
    const out = stringify('yarn-classic', parse('yarn-classic', lf))
    expect(out).toContain('resolved "git+ssh://git@github.com/example/from-git.git#0123456789abcdef0123456789abcdef01234567"')
  })

  it('git:// and scp-like git@ resolved lines also round-trip on emit (F2)', () => {
    const gitProto =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      '"ws@git://github.com/frozeman/WebSocket-Node.git":\n' +
      '  version "1.0.0"\n' +
      '  resolved "git://github.com/frozeman/WebSocket-Node.git#deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"\n'
    expect(stringify('yarn-classic', parse('yarn-classic', gitProto)))
      .toContain('resolved "git://github.com/frozeman/WebSocket-Node.git#deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"')

    const scp =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      '"from-git@git@github.com:example/from-git.git":\n' +
      '  version "0.0.0"\n' +
      '  resolved "git@github.com:example/from-git.git#0123456789abcdef0123456789abcdef01234567"\n'
    expect(stringify('yarn-classic', parse('yarn-classic', scp)))
      .toContain('resolved "git@github.com:example/from-git.git#0123456789abcdef0123456789abcdef01234567"')
  })
})

describe('yarn-classic robustness — duplicate descriptors that should merge', () => {
  const dupBlocks = (resolvedA: string, resolvedB: string, integA = ANSI_SRI, integB = ANSI_SRI): string =>
    '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
    'ansi-styles@^4.0.0:\n' +
    '  version "4.3.0"\n' +
    `  resolved "${resolvedA}"\n` +
    `  integrity ${integA}\n\n` +
    'ansi-styles@^4.1.0:\n' +
    '  version "4.3.0"\n' +
    `  resolved "${resolvedB}"\n` +
    `  integrity ${integB}\n`

  const REG = 'https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz'

  it('two blocks resolving to the same name@version with identical resolution merge into one node', () => {
    const g = parse('yarn-classic', dupBlocks(REG, REG))
    expect(g.byName('ansi-styles')).toHaveLength(1)
    expect(g.getNode('ansi-styles@4.3.0')).toBeDefined()
  })

  it('the merged node re-emits BOTH descriptor keys on one entry', () => {
    const out = stringify('yarn-classic', parse('yarn-classic', dupBlocks(REG, REG)))
    expect(out).toContain('ansi-styles@^4.0.0')
    expect(out).toContain('ansi-styles@^4.1.0')
    // one entry block, not two: the version line appears once.
    expect(out.match(/version "4\.3\.0"/g)).toHaveLength(1)
  })

  it('two blocks at the same name@version from DIFFERENT sources become DISTINCT nodes (ADR-0032 #2b)', () => {
    // Pre-ADR-0032 this collapsed onto one NodeId and threw IRREDUCIBLE_LOSS
    // (data-loss prevention). Now the non-registry copy carries a `+src=`
    // discriminator, so the registry artefact and the example.com artefact are
    // genuinely DISTINCT nodes — the #2b collapse is resolved, not aborted.
    const distinct = dupBlocks(REG, 'https://example.com/other-ansi-styles-4.3.0.tgz')
    const g = parse('yarn-classic', distinct)
    const ids = g.byName('ansi-styles')
    expect(ids).toHaveLength(2)
    // The registry copy is BARE; the example.com copy carries `+src=`.
    expect(ids.some(id => id === 'ansi-styles@4.3.0')).toBe(true)
    expect(ids.some(id => id.startsWith('ansi-styles@4.3.0+src='))).toBe(true)
  })

  it('a TRUE irreducible conflict (same SOURCE, differing integrity) still throws IRREDUCIBLE_LOSS', () => {
    // Both copies resolve to the registry default (both BARE NodeIds — `+src=`
    // cannot tell them apart), but carry different integrity: a genuine
    // collision the discriminator does not resolve, so the loud abort stands.
    const conflict = dupBlocks(REG, REG, sri512('A'), sri512('B'))
    expect(() => parse('yarn-classic', conflict)).toThrow(/collapse onto NodeId ansi-styles@4\.3\.0/)
  })
})

describe('yarn-classic robustness — entry immediately after the header', () => {
  it('an entry on the line right after `# yarn lockfile v1` parses (old yarn / lodash)', () => {
    const lf =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n' +
      '# yarn lockfile v1\n' +
      'abbrev@1, abbrev@1.0.x:\n' +
      '  version "1.0.9"\n' +
      '  resolved "https://registry.yarnpkg.com/abbrev/-/abbrev-1.0.9.tgz#91b4792588a7738c25f35dd6f63752a2f8776135"\n'
    const g = parse('yarn-classic', lf)
    expect(g.getNode('abbrev@1.0.9')).toBeDefined()
  })
})

const H =
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n'

// #83 finding 1 — relative file:/link:/portal: in `resolved`. GENUINE: yarn 1
// writes `resolved: remote.resolved` verbatim for copy/link references, so a
// local dep's `resolved` is the bare specifier (no `://`). The scheme-only
// resolvable-URL predicate rejected it → whole-file parse abort. Now accepted,
// canonicalised to a `directory` resolution, and re-emitted verbatim (the
// link/portal/file distinction survives the round-trip — a `directory`
// canonical alone would flatten all three to `file:`).
describe('yarn-classic robustness — relative file:/link:/portal: resolved', () => {
  const localBlock = (protocol: 'file' | 'link' | 'portal', spec: string, version = '0.0.0'): string =>
    H +
    `"my-lib@${protocol}:${spec}":\n` +
    `  version "${version}"\n` +
    `  resolved "${protocol}:${spec}"\n`

  for (const protocol of ['file', 'link', 'portal'] as const) {
    it(`${protocol}: relative resolved parses (directory canonical), does not abort`, () => {
      const g = parse('yarn-classic', localBlock(protocol, '../my-lib'))
      const node = g.getNode('my-lib@0.0.0')
      expect(node).toBeDefined()
      expect(g.tarballOf('my-lib@0.0.0')?.nativeResolution).toBe(`${protocol}:../my-lib`)
      expect(g.tarballOf('my-lib@0.0.0')?.resolution).toEqual({ type: 'directory', path: '../my-lib' })
      // A recognised local specifier is NOT an unknown resolution.
      expect(g.diagnostics().some(d => d.code === 'RECIPE_RESOLUTION_UNKNOWN')).toBe(false)
    })

    it(`${protocol}: relative resolved round-trips verbatim`, () => {
      const out = stringify('yarn-classic', parse('yarn-classic', localBlock(protocol, '../my-lib')))
      expect(out).toContain(`resolved "${protocol}:../my-lib"`)
      // Idempotent.
      expect(stringify('yarn-classic', parse('yarn-classic', out))).toBe(out)
    })
  }

  it('a file: dep with a dependencies block + version round-trips', () => {
    const lf =
      H +
      '"@scope/local@file:./packages/local":\n' +
      '  version "2.3.4"\n' +
      '  resolved "file:./packages/local"\n' +
      '  dependencies:\n' +
      '    lodash "^4.17.21"\n\n' +
      'lodash@^4.17.21:\n' +
      '  version "4.17.21"\n' +
      '  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffaae8454cf0b3df370c3d6911c"\n'
    const g = parse('yarn-classic', lf)
    expect(g.tarballOf('@scope/local@2.3.4')?.nativeResolution).toBe('file:./packages/local')
    // the file: dep's dependency edge resolves to the registry lodash node.
    expect(g.out('@scope/local@2.3.4').map(e => e.dst)).toContain('lodash@4.17.21')
    const out = stringify('yarn-classic', g)
    expect(stringify('yarn-classic', parse('yarn-classic', out))).toBe(out)
  })

  it('a degenerate `file:` / `link:` with no body is still rejected (not a usable specifier)', () => {
    const lf = H + '"x@file:":\n  version "0.0.0"\n  resolved "file:"\n'
    expect(() => parse('yarn-classic', lf)).toThrow(/unsupported resolved URL/)
  })
})

// #83 finding 2 — source-authored bare package-name entry keys (`foo:` with no
// `@range`). Seven independent producer locks in the external corpus carry this
// shape. The key is accepted as package identity with an explicitly absent
// range; malformed pseudo-scopes remain rejected rather than broadening the
// grammar to arbitrary bare strings.
describe('yarn-classic robustness — source-authored bare package-name entry keys', () => {
  it('still rejects a malformed pseudo-scope through the public parse boundary', () => {
    const lf = H + '"@foo":\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz#aaa"\n'
    expect(() => parse('yarn-classic', lf)).toThrow(LockfileError)
    expect(() => parse('yarn-classic', lf)).toThrow(/bad entry-spec/)
  })

  it('a normal `name@range` key still parses (no regression)', () => {
    const lf = H + 'foo@^1.0.0:\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz#aaa"\n'
    expect(parse('yarn-classic', lf).getNode('foo@1.0.0')).toBeDefined()
  })
})

// #83 finding 3 — quoted field-keys. VERDICT: GARBAGE (not a yarn.lock). yarn 1
// quotes string VALUES but never field KEYS (`version` / `resolved` /
// `integrity` are emitted bare). A quoted key at field position is the
// signature of a yarn-error.log "Lockfile:" dump (yarn's reporter re-indents
// the lockfile under that heading) or an otherwise mangled file. The parser
// rejects cleanly rather than bending to accept non-lockfiles.
describe('yarn-classic robustness — quoted field-keys (error-log dump / garbage)', () => {
  it('rejects quoted `"version"` / `"resolved"` field-keys with a clear diagnostic', () => {
    const lf = H + 'foo@^1.0.0:\n  "version" "1.0.0"\n  "resolved" "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz#aaa"\n'
    expect(() => parse('yarn-classic', lf)).toThrow(LockfileError)
    expect(() => parse('yarn-classic', lf)).toThrow(/quoted field-key.*not valid yarn-classic/)
  })

  it('a full yarn-error.log (no v1 header) is rejected as FORMAT_MISMATCH, not a crash', () => {
    const errlog =
      'Arguments: \n  /usr/bin/node /usr/bin/yarn install\n\n' +
      'PATH: \n  /usr/local/bin:/usr/bin\n\n' +
      'Yarn version: \n  1.22.19\n\n' +
      'Lockfile: \n' +
      '  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n' +
      '  # yarn lockfile v1\n'
    expect(detect(errlog)).toBeUndefined()
    expect(() => parse('yarn-classic', errlog)).toThrow(/expected yarn-classic lockfile v1 header/)
  })
})

// F5 (#92) — quoted multi-hash integrity. VERDICT: GENUINE → FIXED. yarn 1
// quotes any value containing a space, so a space-separated multi-hash SRI
// (`integrity "sha1-… sha512-…"`, the gatsby-era shape when the registry served
// both a legacy sha1 and a sha512) is written QUOTED. The pre-fix parser
// captured the value verbatim INCLUDING the surrounding quotes, so the stray `"`
// glued onto the first/last members and `parseSri` skipped EVERY hash — a silent,
// security-relevant integrity loss (both the sha1 and the recoverable sha512
// vanished). Now the quoted value is un-quoted, every algorithm is preserved
// under the shared multi-hash multiset, and emit re-quotes the multi-hash form
// for a byte-faithful round-trip.
describe('yarn-classic robustness — quoted multi-hash integrity (F5/#92)', () => {
  const multiHashLock = (sha1: string, sha512: string): string =>
    H +
    'caniuse-lite@^1.0.30000844:\n' +
    '  version "1.0.30000865"\n' +
    '  resolved "https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30000865.tgz#70026616e8afe6e1442f8bb4e1092987d81a2f25"\n' +
    `  integrity "${sha1} ${sha512}"\n`

  it('preserves BOTH the sha1 and the sha512 of a quoted multi-hash integrity (not dropped)', () => {
    const sha1 = sri1('caniuse-lite')
    const sha512 = sri512('caniuse-lite')
    const g = parse('yarn-classic', multiHashLock(sha1, sha512))
    const integrity = g.tarballOf('caniuse-lite@1.0.30000865')?.integrity
    expect(integrity).toBeDefined()
    expect(integrity!.hashes.map(h => h.algorithm).sort()).toEqual(['sha1', 'sha512'])
    // Neither member is dropped → no invalid-integrity diagnostic.
    expect(g.diagnostics().some(d => d.code === 'YARN_CLASSIC_INVALID_INTEGRITY')).toBe(false)
  })

  it('re-emits the multi-hash integrity QUOTED and round-trips byte-stably', () => {
    const sha1 = sri1('abbrev')
    const sha512 = sri512('abbrev')
    const out = stringify('yarn-classic', parse('yarn-classic', multiHashLock(sha1, sha512)))
    expect(out).toContain(`integrity "${sha1} ${sha512}"`)
    expect(stringify('yarn-classic', parse('yarn-classic', out))).toBe(out)
  })

  it('a single-hash integrity still emits BARE (unquoted) — no regression', () => {
    const lf =
      H +
      'ms@^2.1.3:\n' +
      '  version "2.1.3"\n' +
      '  resolved "https://registry.yarnpkg.com/ms/-/ms-2.1.3.tgz#574c8138ce1d2b5861f0b44579dbadd60c6615b2"\n' +
      `  integrity ${ANSI_SRI}\n`
    const out = stringify('yarn-classic', parse('yarn-classic', lf))
    expect(out).toContain(`  integrity ${ANSI_SRI}`)
    expect(out).not.toContain(`integrity "${ANSI_SRI}"`)
  })
})

// F6 (#93) — npm-aliased entry node identity. VERDICT: GENUINE → FIXED. yarn 1
// encodes an npm-alias as `"<alias>@npm:<target>@<range>"`; the RESOLVED package
// (the node identity) is `<target>`, while `<alias>` lives only as a
// consumer-facing descriptor name. The pre-fix parser keyed the node off the
// descriptor's `<alias>` name, minting a PHANTOM `<alias>@<version>` node split
// from the real `<target>@<version>` — the same registry tarball duplicated. Now
// the alias descriptor groups under its target (one node), the descriptor is
// indexed so a consumer that declares it still resolves there, and the
// consumer's edge records `attrs.alias` so the entry-key + dependency line
// re-key under the alias on emit. (Distinct from the berry npm:-alias case #76 —
// this is classic, which has no `resolution:` field to derive the target from.)
describe('yarn-classic robustness — npm-alias entry identity (F6/#93)', () => {
  const sw = 'sha512-wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g=='

  const trioEntry =
    '"string-width-cjs@npm:string-width@^4.2.0", string-width@^4.1.0, string-width@^4.2.0:\n' +
    '  version "4.2.3"\n' +
    '  resolved "https://registry.yarnpkg.com/string-width/-/string-width-4.2.3.tgz#269c7117d27b05ad2e536830a8ec895ef9c6d010"\n' +
    `  integrity ${sw}\n`

  it('an npm-aliased entry collapses to ONE node keyed by the alias TARGET (no duplicate)', () => {
    const g = parse('yarn-classic', H + trioEntry)
    // Exactly one string-width node, identified by the target name — NOT a split
    // `string-width-cjs@4.2.3` + `string-width@4.2.3` pair.
    expect(g.byName('string-width')).toEqual(['string-width@4.2.3'])
    expect(g.byName('string-width-cjs')).toEqual([])
    expect(g.getNode('string-width@4.2.3')?.name).toBe('string-width')
  })

  it('a consumer declaring the alias resolves to the target node, with attrs.alias recorded', () => {
    const lf =
      H +
      '"@isaacs/cliui@^8.0.2":\n' +
      '  version "8.0.2"\n' +
      '  resolved "https://registry.yarnpkg.com/@isaacs/cliui/-/cliui-8.0.2.tgz#b37667b7bc181c168782259bab42474fbf52b550"\n' +
      '  integrity sha512-O8jcjabXaleOG9DQ0+ARXWZBTfnP4WNAqzuiJK7ll44AmxGKv/J2M4TPjxjY3znBCfvBXFzucm1twdyFybyWtA==\n' +
      '  dependencies:\n' +
      '    string-width-cjs "npm:string-width@^4.2.0"\n\n' +
      trioEntry
    const g = parse('yarn-classic', lf)
    const edges = g.out('@isaacs/cliui@8.0.2', 'dep')
    expect(edges).toHaveLength(1)
    expect(edges[0]!.dst).toBe('string-width@4.2.3')
    expect(edges[0]!.attrs?.alias).toBe('string-width-cjs')
    expect(edges[0]!.attrs?.range).toBe('npm:string-width@^4.2.0')
  })

  it('re-emits the alias descriptor on the entry key + the alias dep line, round-trip stable', () => {
    const lf =
      H +
      '"@isaacs/cliui@^8.0.2":\n' +
      '  version "8.0.2"\n' +
      '  resolved "https://registry.yarnpkg.com/@isaacs/cliui/-/cliui-8.0.2.tgz#b37667b7bc181c168782259bab42474fbf52b550"\n' +
      '  integrity sha512-O8jcjabXaleOG9DQ0+ARXWZBTfnP4WNAqzuiJK7ll44AmxGKv/J2M4TPjxjY3znBCfvBXFzucm1twdyFybyWtA==\n' +
      '  dependencies:\n' +
      '    string-width-cjs "npm:string-width@^4.2.0"\n\n' +
      trioEntry
    const out = stringify('yarn-classic', parse('yarn-classic', lf))
    // The alias descriptor survives on the entry key, and the consumer's dep line
    // keys under the alias with the `npm:` locator value.
    expect(out).toContain('string-width-cjs@npm:string-width@^4.2.0')
    expect(out).toContain('string-width-cjs "npm:string-width@^4.2.0"')
    expect(stringify('yarn-classic', parse('yarn-classic', out))).toBe(out)
  })

  it('does NOT treat the berry default-protocol form `npm:<range>` as an alias (no phantom range-node)', () => {
    // `undici-types@npm:~5.26.4` is the yarn-BERRY default-protocol shape (a bare
    // range under the npm: protocol, SAME name) that can reach classic emit on a
    // cross-family convert. Its npm: body has no embedded `@<range>`, so it is
    // NOT an alias — it must resolve to `undici-types`, never a phantom
    // `~5.26.4@<version>` node.
    const lf =
      H +
      '"undici-types@npm:~5.26.4":\n' +
      '  version "5.26.5"\n' +
      '  resolved "https://registry.yarnpkg.com/undici-types/-/undici-types-5.26.5.tgz#bcd539893d00b56e964fd2657a4866b221a65617"\n' +
      '  integrity sha512-JlCMO+ehdEIKqlFxk6IfVoAUVmgz7cU7zD/h9XZ0qzeosSHmUJVOzSQvvYSYWXkFXC+IfLKSIffhv0sVZup6pA==\n'
    const g = parse('yarn-classic', lf)
    expect(g.byName('undici-types')).toEqual(['undici-types@5.26.5'])
    expect(Array.from(g.nodes()).map(n => n.id)).toEqual(['undici-types@5.26.5'])
  })
})

// F6 + dist-tag — an npm-aliased dependency whose alias range is a published
// dist-TAG (`<alias> "npm:<target>@latest"`), not a semver range. The two
// behaviours that must hold:
//  (a) entry PRESENT — the aliased entry binds the SINGLE target node; the
//      consumer's edge records `attrs.alias`, and there is exactly one node (the
//      target), no phantom `<alias>@<version>` and no phantom tag node;
//  (b) entry ABSENT — the consumer's alias dep cleanly DROPS with a
//      YARN_CLASSIC_MISSING_ENTRY warning and mints NO node (edges never create
//      nodes; a missed descriptor is dropped, never guessed).
describe('yarn-classic robustness — aliased dist-tag dependency (F6 + dist-tag)', () => {
  const barLatest = 'sha512-wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g=='

  // The aliased target entry — keyed by the verbatim `foo@npm:bar@latest`
  // descriptor (alias `foo`, target `bar`, dist-tag `latest`), resolving to the
  // real bar node.
  const barEntry =
    '"foo@npm:bar@latest":\n' +
    '  version "1.4.0"\n' +
    '  resolved "https://registry.yarnpkg.com/bar/-/bar-1.4.0.tgz#abc1230000000000000000000000000000000000"\n' +
    `  integrity ${barLatest}\n`

  const consumer =
    'app@^1.0.0:\n' +
    '  version "1.0.0"\n' +
    '  resolved "https://registry.yarnpkg.com/app/-/app-1.0.0.tgz#def4560000000000000000000000000000000000"\n' +
    '  integrity sha512-O8jcjabXaleOG9DQ0+ARXWZBTfnP4WNAqzuiJK7ll44AmxGKv/J2M4TPjxjY3znBCfvBXFzucm1twdyFybyWtA==\n' +
    '  dependencies:\n' +
    '    foo "npm:bar@latest"\n'

  it('entry PRESENT — the alias dist-tag dep binds the target node (one node, alias on edge, no phantom)', () => {
    const g = parse('yarn-classic', H + consumer + '\n' + barEntry)
    // Exactly one resolved package for the alias target — keyed by `bar`, NOT a
    // phantom `foo@1.4.0` and NOT a phantom `latest@…` tag node.
    expect(g.byName('bar')).toEqual(['bar@1.4.0'])
    expect(g.byName('foo')).toEqual([])
    expect(g.byName('latest')).toEqual([])
    expect(Array.from(g.nodes()).map(n => n.id).sort()).toEqual(['app@1.0.0', 'bar@1.4.0'])
    // The consumer's edge binds the target with the alias + verbatim locator.
    const edges = g.out('app@1.0.0', 'dep')
    expect(edges).toHaveLength(1)
    expect(edges[0]!.dst).toBe('bar@1.4.0')
    expect(edges[0]!.attrs?.alias).toBe('foo')
    expect(edges[0]!.attrs?.range).toBe('npm:bar@latest')
    // No missing-entry warning when the entry is present.
    expect(g.diagnostics().some(d => d.code === 'YARN_CLASSIC_MISSING_ENTRY')).toBe(false)
  })

  it('entry ABSENT — the alias dist-tag dep drops cleanly (YARN_CLASSIC_MISSING_ENTRY, no phantom)', () => {
    const g = parse('yarn-classic', H + consumer)
    // Only the consumer survives — the unresolved alias dep mints NOTHING.
    expect(Array.from(g.nodes()).map(n => n.id)).toEqual(['app@1.0.0'])
    expect(g.byName('foo')).toEqual([])
    expect(g.byName('bar')).toEqual([])
    expect(g.byName('latest')).toEqual([])
    expect(g.out('app@1.0.0', 'dep')).toHaveLength(0)
    // The drop is attributed by a missing-entry warning.
    expect(
      g.diagnostics().some(d => d.code === 'YARN_CLASSIC_MISSING_ENTRY' && /foo@npm:bar@latest/.test(d.message)),
    ).toBe(true)
    // F8 — the absent dep mints no edge/node (above) BUT the verbatim dependency
    // line is preserved through the per-node sidecar so a same-format round-trip
    // re-emits it byte-for-byte (preservation ≠ binding — it never becomes a node).
    const out = stringify('yarn-classic', g)
    expect(out).toContain('foo "npm:bar@latest"')
  })
})

// F8 — a dependency whose TARGET is genuinely ABSENT from the lock (no entry, no
// candidate to bind) must round-trip its dependency line VERBATIM on a
// same-format pass, mirroring the yarn-berry F8/#103 `unresolvedDeps` mechanism.
// The descriptor mints NO edge and NO phantom node (identity stays clean) and the
// YARN_CLASSIC_MISSING_ENTRY diagnostic still fires — preservation keeps BOTH the
// bytes and the signal. This is DISTINCT from the dist-tag case where the target
// EXISTS (that binds a real edge, tested above): only the genuinely-absent ref is
// preserved verbatim; an AMBIGUOUS miss stays dropped (never resurrected).
describe('yarn-classic robustness — absent-target dep preserved verbatim (F8)', () => {
  const lf =
    H +
    'pkg-a@^1.0.0:\n' +
    '  version "1.0.0"\n' +
    '  resolved "https://registry.yarnpkg.com/pkg-a/-/pkg-a-1.0.0.tgz#deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"\n' +
    '  dependencies:\n' +
    '    missing-dep "^1.0.0"\n' +
    '    other-missing "~2.0.0"\n' +
    '  optionalDependencies:\n' +
    '    opt-missing "^3.0.0"\n'

  it('re-emits the absent dep + optional lines verbatim; mints no node; warns', () => {
    const g = parse('yarn-classic', lf)
    // No phantom nodes for any absent target.
    expect(Array.from(g.nodes()).map(n => n.id)).toEqual(['pkg-a@1.0.0'])
    expect(g.byName('missing-dep')).toEqual([])
    expect(g.byName('other-missing')).toEqual([])
    expect(g.byName('opt-missing')).toEqual([])
    // No edges bound.
    expect(g.out('pkg-a@1.0.0')).toHaveLength(0)
    // The missing-entry diagnostic still fires for every absent dep.
    const missing = g.diagnostics().filter(d => d.code === 'YARN_CLASSIC_MISSING_ENTRY')
    expect(missing.length).toBe(3)
    // Verbatim re-emit into the matching block.
    const out = stringify('yarn-classic', g)
    expect(out).toContain('  dependencies:')
    expect(out).toContain('    missing-dep "^1.0.0"')
    expect(out).toContain('    other-missing "~2.0.0"')
    expect(out).toContain('  optionalDependencies:')
    expect(out).toContain('    opt-missing "^3.0.0"')
  })

  it('round-trip is idempotent (byte-stable on re-parse + re-stringify)', () => {
    const out1 = stringify('yarn-classic', parse('yarn-classic', lf))
    const out2 = stringify('yarn-classic', parse('yarn-classic', out1))
    expect(out2).toBe(out1)
  })

  it('an AMBIGUOUS dist-tag (≥2 siblings) stays DROPPED — not preserved verbatim', () => {
    const ambig =
      H +
      'dup@1.0.0:\n' +
      '  version "1.0.0"\n' +
      '  resolved "https://registry.yarnpkg.com/dup/-/dup-1.0.0.tgz#1111111111111111111111111111111111111111"\n' +
      'dup@2.0.0:\n' +
      '  version "2.0.0"\n' +
      '  resolved "https://registry.yarnpkg.com/dup/-/dup-2.0.0.tgz#2222222222222222222222222222222222222222"\n' +
      'consumer@^1.0.0:\n' +
      '  version "1.0.0"\n' +
      '  resolved "https://registry.yarnpkg.com/consumer/-/consumer-1.0.0.tgz#3333333333333333333333333333333333333333"\n' +
      '  dependencies:\n' +
      '    dup latest\n'
    const g = parse('yarn-classic', ambig)
    const out = stringify('yarn-classic', g)
    // The ambiguous dep is NOT re-emitted (preservation is genuinely-absent only).
    expect(out).not.toContain('dup "latest"')
    expect(out).not.toContain('dup latest')
    // It is diagnosed as ambiguous, not preserved.
    expect(g.diagnostics().some(d => /AMBIGUOUS/.test(d.code))).toBe(true)
  })
})

// D1 (#94) — detect() structural fallback. VERDICT: GENUINE → FIXED. The two
// header comment lines (`# THIS IS AN AUTOGENERATED FILE…` + `# yarn lockfile
// v1`) can be displaced by a tool-prepended comment or stripped entirely, and
// the pre-fix `detect()` then returned `undefined` (no structural fallback). The
// fallback recognises the classic entry-block SHAPE — a col-0 `<name>@<range>:`
// descriptor immediately followed by `  version "<x>"` — which no npm/pnpm/bun
// lockfile emits, so the #83 garbage-rejection boundary stays intact.
describe('yarn-classic robustness — header-less detect fallback (D1/#94)', () => {
  const body =
    'lodash@^4.17.21:\n' +
    '  version "4.17.21"\n' +
    '  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffaae8454cf0b3df370c3d6911c"\n' +
    `  integrity ${sri512('lodash')}\n`

  it('detects a header-less body via the entry-block structural fallback, and parses it', () => {
    expect(detect(body)).toBe('yarn-classic')
    expect(parse('yarn-classic', body).getNode('lodash@4.17.21')).toBeDefined()
  })

  it('detects when a foreign comment is prepended before (or instead of) the header', () => {
    const withForeignComment = '# generated by some-tool\n' + body
    expect(detect(withForeignComment)).toBe('yarn-classic')
    expect(parse('yarn-classic', withForeignComment).getNode('lodash@4.17.21')).toBeDefined()
  })

  it('does NOT false-positive non-classic inputs (garbage boundary intact)', () => {
    // pnpm-ish YAML (`version:` colon form, no quotes; no lockfileVersion).
    expect(detect('importers:\n  .:\n    dependencies:\n      a:\n        specifier: ^1\n        version: 1.0.0\n')).toBeUndefined()
    // plain YAML with a colon `version:` value.
    expect(detect('name: x\nversion: 1.0.0\n')).toBeUndefined()
    // JSON (npm / bun shape).
    expect(detect('{\n  "name": "x",\n  "version": "1.0.0"\n}\n')).toBeUndefined()
    // a bare-name entry key (#83 malformed) does not adopt the fallback.
    expect(detect('foo:\n  version "1.0.0"\n')).toBeUndefined()
    // a yarn-error.log dump re-indents the lock (entry keys NOT at col 0).
    const errlog =
      'Arguments: \n  /usr/bin/node /usr/bin/yarn install\n\n' +
      'Lockfile: \n' +
      '  lodash@^4.17.21:\n    version "4.17.21"\n'
    expect(detect(errlog)).toBeUndefined()
  })
})
